import type { MediterraneanCardDefinition, MediterraneanChoice } from './deck';

const c=(idSuffix:string,label:string,description:string,effects:any[]):MediterraneanChoice=>({idSuffix,label,description,effects});
const change=(key:string,delta:number)=>({type:'CHANGE_VARIABLE',key,delta} as const);
const days=(n:number)=>({type:'ADVANCE_DAYS',days:n} as const);
const flag=(key:string)=>({type:'SET_FLAG',key,value:true} as const);

const directReplyByTopic = (topic:number, side:0|1) => {
  const replies: Array<[string,string]> = [
    ['İşaretin neyi gösterdiğini bana anlat.', 'Bu işareti başka bir kayıtta da doğrulayacağım.'],
    ['Fiyatın neden değiştiğini açıkça söyle.', 'Bu değişiklikten kimin kazandığını bilmek istiyorum.'],
    ['Sözün asıl anlamını bana aktar.', 'Çeviriyi başka bir tercümanla da karşılaştıracağım.'],
    ['Kayıttaki eksikliği bana göster.', 'Bu kaydın neden değiştiğini araştıracağım.'],
    ['Hangi limandan geldiğini anlat.', 'Aynı haberi başka bir yolcudan da dinleyeceğim.'],
    ['Denizde ne gördüğünü baştan anlat.', 'Bu haberi başka bir denizciden de doğrulayacağım.'],
    ['İki kaynağın neden ayrıldığını açıkla.', 'İkisini de ayrı ayrı dinleyeceğim.'],
    ['Beni tanıştıracağın tüccarın şartlarını anlat.', 'Önce onunla neden iş yaptığını bilmek istiyorum.'],
    ['Eski kaydın bana ne söylediğini göster.', 'Kayıttaki ismi başka bir yerden doğrulayacağım.'],
    ['Benden hangi bilgiyi istediğinizi açıkça söyleyin.', 'Kimlerle görüştüğümü size anlatmayacağım.'],
    ['Kaç kaynağa baktığımı sana söyleyeceğim; ama hepsini açıklamayacağım.', 'Önce senin hangi kaynaklara güvendiğini öğrenmek istiyorum.'],
    ['Beni kiminle görüştüreceğini söyle.', 'Önce bu kişinin neden önemli olduğunu anlat.'],
    ['Evdekilerin neye ihtiyacı olduğunu anlat.', 'Onlara haber göndermenin yolunu bulacağım.'],
    ['Limanın ne konuştuğunu anlat.', 'Söylentiyi büyütmeden önce kaynağını bulacağım.'],
    ['Haberi kime ulaştıracağını açıkça söyle.', 'Mesajın kimlerin elinden geçeceğini bilmek istiyorum.'],
    ['Malın gerçek değerini ve fiyatın neden değiştiğini anlat.', 'Bu alışverişte kimin çıkarı olduğunu öğrenmeden karar vermem.'],
    ['Rotanın neden uzadığını anlat.', 'Tayfanın ve geminin durumunu önce göreceğim.'],
    ['Mektubun kimden geldiğini ve kime gideceğini söyle.', 'Bu yazıyı başka bir gözün de okuyup okumadığını bilmek istiyorum.'],
    ['Haberi kime ulaştıracağımızı söyle.', 'Önce bu haberin değerini ve riskini anlayacağım.'],
    ['Kayıtla haber arasındaki farkı bana göster.', 'Hangisinin eski olduğunu araştıracağım.'],
    ['Ragusa bağlantısının ne getirdiğini anlat.', 'Bu haberi başka bir tüccardan da doğrulayacağım.'],
    ['İki yolcunun neden birbirini tanımadığını anlat.', 'İkisinin de geçmişini ayrı ayrı dinleyeceğim.'],
    ['Benden tam olarak ne öğrenmek istediğinizi söyleyin.', 'Bana sorulanı cevaplamadan önce sebebini bilmek istiyorum.'],
    ['Evdekilerin neden beklediğini anlat.', 'Onlara haber göndermenin güvenli yolunu bulacağım.'],
    ['Limanda gördüğün kişileri ve gemileri anlat.', 'Bu bilgiyi kiminle paylaşacağımı ben seçeceğim.'],
    ['Mektubun neden geciktiğini anlat.', 'Haberin doğruluğunu gecikmeden bağımsız kontrol edeceğim.'],
    ['Beni tanıştıracağın iki tarafın şartlarını anlat.', 'Önce ikisinin de ne istediğini öğrenmek istiyorum.'],
    ['Eski bağlantının neden geri döndüğünü anlat.', 'Bu kişiye yeniden güvenmeden önce geçmişini kontrol edeceğim.'],
    ['Bu kadar farklı haber arasında hangisini doğruladığını söyle.', 'Ben tek bir söze güvenmeden önce kaynakları karşılaştıracağım.'],
  ];
  return replies[topic % replies.length][side];
};

const topics=[
['Bir kâtip','Yazıcı','Bu işaretin ne anlama geldiğini sen de biliyor musun?','INTELLIGENCE','information','language'],
['Bir tüccar','Tüccar','Bu fiyat değişikliğinin sebebini duydun mu?','TRADE','money','merchantNetwork'],
['Bir tercüman','Tercüman','Bu sözü başka türlü de çevirebilir miyiz?','IDENTITY','language','information'],
['Bir kayıt görevlisi','Kâtip','Şu kayıtta bir eksik var. Sence neden?','PORT','information','reputation'],
['Bir yolcu','Yolcu','Gittiğim limanda herkes başka bir şey söylüyordu.','INTELLIGENCE','information','social'],
['Bir denizci','Denizci','Denizde duyduğum haberi burada da duydum.','SEA','sailorNetwork','information'],
['Bir aracı','Aracı','İki kişi aynı haberi farklı anlatıyor. Hangisine bakalım?','INTELLIGENCE','information','reputation'],
['Bir komisyoncu','Aracı','Seni başka bir tüccarla tanıştırabilirim.','TRADE','merchantNetwork','social'],
['Bir kâtip','Kayıt görevlisi','Eski bir kayıtta bugün işimize yarayacak bir iz var.','PORT','information','reputation'],
['Bir görevli','Görevli','Sana gelen haberin kaynağını da bilmek isteriz.','INTELLIGENCE','safety','intelligenceNetwork'],
['Bir danışman','Danışman','Bir karar vermeden önce kaç kaynağa baktın?','INTELLIGENCE','information','reputation'],
['Bir ziyaretçi','Ziyaretçi','Burada kiminle görüşmem gerektiğini söyleyebilir misin?','IDENTITY','social','reputation'],
['Bir aile büyüğü','Aileden biri','Evdekiler senden haber bekliyor.','FAMILY','familyTies','social'],
['Bir liman sakini','Tanıdık','Son günlerde limanda çok şey konuşuluyor.','PORT','information','social'],
['Bir haberci','Haberci','Bu haberi kime ulaştırmamı istersin?','INTELLIGENCE','intelligenceNetwork','reputation'],
['Bir tüccar','Tüccar','Bir malın fiyatı değiştiğinde herkes başka sebep söylüyor.','TRADE','money','information'],
['Bir denizci','Denizci','Yol uzadı. Sence şimdi ne yapmalıyız?','SEA','safety','sailorNetwork'],
['Bir mütercim','Mütercim','Bu mektubu kimlerin okuyabileceğini düşünüyorsun?','IDENTITY','language','safety'],
['Bir aracı','Aracı','Bir haberin değeri, kime ulaştığına göre değişiyor.','INTELLIGENCE','information','social'],
['Bir kâtip','Kâtip','Eski kayıtlarla yeni haber birbirini tutmuyor.','PORT','information','safety'],
['Bir tüccar','Tüccar','Ragusa üzerinden gelen haber sana da ulaştı mı?','TRADE','merchantNetwork','information'],
['Bir yolcu','Yolcu','Aynı şehirden gelen iki kişi birbirini tanımıyor.','IDENTITY','language','social'],
['Bir görevli','Görevli','Bugün senden yalnızca bir şey öğrenmek istiyorum.','INTELLIGENCE','safety','information'],
['Bir aileden biri','Aile çevresi','Bu kadar uzun süre uzakta kalmak zorunda mısın?','FAMILY','familyTies','safety'],
['Bir liman işçisi','Liman işçisi','Burada olan biteni en çok biz görüyoruz.','PORT','portReputation','information'],
['Bir yazıcı','Yazıcı','Mektup gecikirse haberin değeri de değişir.','INTELLIGENCE','language','information'],
['Bir komisyoncu','Komisyoncu','İki tarafı da tanıyorum. İstersen seni tanıştırayım.','TRADE','merchantNetwork','reputation'],
['Bir denizci','Denizci','Döndüğüm limanda herkes yeni bir haber bekliyordu.','SEA','sailorNetwork','information'],
['Bir tanıdık','Tanıdık','Eski bağlantılarından biri yeniden ortaya çıktı.','INTELLIGENCE','social','intelligenceNetwork'],
['Bir danışman','Danışman','Bazen en önemli karar, hangi haberi dikkate alacağını seçmektir.','INTELLIGENCE','information','reputation'],
];

const questionSets: Record<MediterraneanCardDefinition['category'], Array<[string, string]>> = {
  INTELLIGENCE: [
    ['Bunu kimden duydun?', 'Bir kaynağı daha kontrol edelim mi?'],
    ['Bu haber ne kadar yeni?', 'Bunu başka kim doğruluyor?'],
    ['Bu kişinin bağlantısı kim?', 'Kimlerle görüştüğünü biliyor musun?'],
    ['Bunu kayıtlarda bulabilir miyiz?', 'Eski haberlerle karşılaştırayım mı?'],
    ['Benden ne bekliyorsun?', 'Bunu neden bana anlatıyorsun?'],
    ['Bu bilginin bedeli ne?', 'Karşılığında ne istiyorsun?'],
    ['Bunu kimlerin bilmesi gerekiyor?', 'Bu haberi kimden saklayalım?'],
    ['Başka limanlarda da böyle mi?', 'Aynı haberi başka yerde duydun mu?'],
    ['Şimdi ne yapmamı bekliyorsun?', 'Önce biraz daha bekleyelim mi?'],
    ['Buna güvenmeli miyim?', 'Sen olsan neyi kontrol ederdin?'],
  ],
  TRADE: [
    ['Fiyat neden değişti?', 'Bu değişiklikten kim kazanıyor?'],
    ['Bu malı nereden bulacağız?', 'Bu işten ne kadar kazanacağım?'],
    ['Borcu ne zaman kapatacağız?', 'Yeni bir borca girmeli miyiz?'],
    ['Bu tüccara ne kadar güveniyorsun?', 'Başka bir ortak bulalım mı?'],
    ['Hangi liman daha kazançlı?', 'Bu rotanın riski ne?'],
    ['Bu haber ticareti nasıl etkiler?', 'Beklemek daha mı doğru?'],
    ['Bu bağlantının karşılığı ne?', 'Benden ne bekliyorsun?'],
    ['Hesabı kim tutuyor?', 'Kayıtları tekrar kontrol edelim mi?'],
    ['Bu işi tek başına mı yürütüyorsun?', 'Başka kim bu işin içinde?'],
    ['Şimdi alıp bekleyelim mi?', 'Önce piyasayı biraz daha izleyelim mi?'],
  ],
  IDENTITY: [
    ['Bu sözün asıl anlamı ne?', 'Bunu kim doğrulayabilir?'],
    ['Bu dili nerede öğrendin?', 'Bana da öğretebilir misin?'],
    ['Bu kişi seni nereden tanıyor?', 'Aranızdaki bağ ne?'],
    ['İki tarafla da konuşuyor musun?', 'Bir tarafı seçmek zorunda mıyız?'],
    ['Bunu nasıl çevirelim?', 'Sözün bağlamını da öğrenelim mi?'],
    ['Bu çevrede sana kim güveniyor?', 'Benim için kimi tanıştırabilirsin?'],
    ['Geçmişini ne kadar anlatmak istiyorsun?', 'Bugünkü hayatın nasıl değişti?'],
    ['Bu bağlantıyı ne kadar sürdürebiliriz?', 'Mesafeyi korumak daha mı güvenli?'],
    ['Beni hangi çevreye sokuyorsun?', 'Bu çevrede kim söz sahibi?'],
    ['İki dünyanın arasında kalmak zor mu?', 'Yeni hayatını nasıl kurdun?'],
  ],
  PORT: [
    ['Kayıtta ne eksik?', 'Bu kaydı neden değiştirelim?'],
    ['Limanda ne gördün?', 'Bunu kimlerle paylaşmalıyım?'],
    ['Bu yük neden bekliyor?', 'Kimden izin almamız gerekiyor?'],
    ['Kimler bugün limana geldi?', 'Giriş kayıtlarını kontrol edelim mi?'],
    ['Bu haber limanda kimleri etkiler?', 'Önce sessizce araştıralım mı?'],
    ['Adım neden kayıtlarda geçiyor?', 'Görünürlüğümü azaltmalı mıyım?'],
    ['Bu yük kime ait?', 'Sahibini nasıl doğrulayacağız?'],
    ['Limandaki söylenti nereden çıktı?', 'Başka bir kaynağa soralım mı?'],
    ['Bu iş için kimden yardım alabiliriz?', 'Tek başımıza ilerlemek daha mı güvenli?'],
    ['Bugün limanda ne değişti?', 'Dünle karşılaştırabilir miyiz?'],
  ],
  SEA: [
    ['Bu gemi nereye gidiyor?', 'Bu bilgiyi sana kim verdi?'],
    ['Seferde ne eksik?', 'Neden şimdi yola çıkalım?'],
    ['Tayfa ne düşünüyor?', 'Kaptanla tekrar konuşalım mı?'],
    ['Bu yolculuk ne kadar sürecek?', 'Karada kalmak daha mı güvenli?'],
    ['Hangi limanda duracağız?', 'Rotayı değiştirmek gerekir mi?'],
    ['Denizde ne gördün?', 'Başka denizciler de bunu anlattı mı?'],
    ['Tayfaya kim güveniyor?', 'Aralarında sorun mu var?'],
    ['Yol uzarsa ne yapacağız?', 'Erzakı yeniden hesaplayalım mı?'],
    ['Bu gemide kimin sözü geçiyor?', 'Kaptanla açıkça konuşalım mı?'],
    ['Bir sonraki sefer ne zaman?', 'Bu kez karada kalmalı mıyım?'],
  ],
  FAMILY: [
    ['Evdekiler benden ne bekliyor?', 'Daha ne kadar uzak kalacağım?'],
    ['Aileye ne kadar gönderebilirim?', 'Önce kendi geçimimizi mi düşünelim?'],
    ['Ne zaman eve döneceğim?', 'Biraz daha burada kalmam gerekir mi?'],
    ['Evdekiler bu haberi biliyor mu?', 'Onları bu işten uzak tutmalı mıyım?'],
    ['Aile bağlarını nasıl koruyacağız?', 'Bu hayatı sürdürmek aileyi zorlar mı?'],
    ['Benden neden haber bekliyorlar?', 'Onlara şimdi dönmek mümkün mü?'],
    ['Bu yolculuk aileyi nasıl etkiler?', 'Başka bir çözüm bulabilir miyiz?'],
    ['Aileden kim bu işi biliyor?', 'Bunu evde konuşmalı mıyız?'],
    ['Yerleşmemi gerçekten istiyor musunuz?', 'Denize dönmem sorun olur mu?'],
    ['Şimdi ne yapmamı istersiniz?', 'Biraz daha zaman verebilir misiniz?'],
  ],
  CAPTIVITY: [
    ['Nerede kaldın?', 'Orada kimlerle konuştun?'],
    ['Döndüğünde ne öğrendin?', 'Geçmişini neden anlatıyorsun?'],
    ['Ailen seni nasıl karşıladı?', 'Yeniden hayata alışmak zor mu?'],
    ['Bu haber nereden geliyor?', 'Başka bir esir de bunu anlattı mı?'],
    ['Sana kim yardım etti?', 'Hâlâ o insanlarla bağlantın var mı?'],
    ['Masrafları nasıl karşılayacaksınız?', 'Yardım için kimlere güveniyorsunuz?'],
    ['Bu deneyim seni nasıl değiştirdi?', 'Bunu konuşmak ister misin?'],
    ['Hangi limanlardan geçtin?', 'Oradaki insanları hatırlıyor musun?'],
    ['Şimdi neye ihtiyacın var?', 'Sana nasıl yardımcı olabiliriz?'],
    ['Eski hayatına dönmek mümkün mü?', 'Yeni bir çevre kurmak mı daha kolay?'],
  ],
};

const placeHints = ['Galata','İstanbul','Ragusa','Venedik','Cezayir','Tunus','Cerbe','Malta','Kıbrıs','İskenderiye'];

export const EXTRA_MEDITERRANEAN_CARDS: MediterraneanCardDefinition[]=topics.flatMap(([speaker,role,line,category,a,b],i)=>Array.from({length:10},(_,j)=>({
 id:`med-extra-${i+1}-${j+1}`,speaker,role,line:`${line} ${placeHints[(i+j)%placeHints.length]}.`,category:category as MediterraneanCardDefinition['category'],weight:4+(j%6),
 left:c('hold',directReplyByTopic(i,0),'Bilgiyi sınayarak ilerle.',[change(a,2+(j%3)),days(40+(j%4)*20)]),
 right:c('answer',directReplyByTopic(i,1),'Konuşmayı sürdür ve yeni bir bağlantı kur.',[change(b,3+(j%4)),change('safety',-1),flag(`extra_${i+1}_${j+1}`),days(50+(j%5)*20)]),
})));

export const EXTRA_MEDITERRANEAN_CARD_COUNT=EXTRA_MEDITERRANEAN_CARDS.length;
