import type { DecisionEffect } from '@/domain/game';
import type { MediterraneanCardDefinition, MediterraneanChoice } from './deck';

const change = (key: string, delta: number): DecisionEffect => ({ type: 'CHANGE_VARIABLE', key, delta });
const flag = (key: string, value = true): DecisionEffect => ({ type: 'SET_FLAG', key, value });
const days = (value: number): DecisionEffect => ({ type: 'ADVANCE_DAYS', days: value });

const c = (idSuffix: string, label: string, description: string, effects: DecisionEffect[]): MediterraneanChoice =>
  ({ idSuffix, label, description, effects });

const H = (
  id: string, speaker: string, role: string, line: string,
  category: MediterraneanCardDefinition['category'],
  left: MediterraneanChoice, right: MediterraneanChoice,
  extra: Partial<MediterraneanCardDefinition> = {},
): MediterraneanCardDefinition => ({
  id, speaker, role, line, category, left, right, weight: 20, ...extra,
});

/**
 * Original game writing informed by the two Emrah Safa Gürkan source books.
 * Historical research is transformed into game situations; source prose is not copied.
 */
export const HISTORICAL_MEDITERRANEAN_CARDS: MediterraneanCardDefinition[] = [
  H('med-history-port', 'Yusuf', 'Liman aracısı',
    'İstanbuldan gelen haberler burada çabuk yayılır. Senin kulağın da açık olsun.', 'INTELLIGENCE',
    c('listen', 'Önce haberi dinleyeyim.', 'Liman çevresindeki bilgi akışına gir.', [change('information', 3), change('social', 2), flag('history_listener'), days(120)]),
    c('work', 'Ben işime bakarım.', 'Daha güvenli bir başlangıç yap.', [change('money', 3), change('safety', 2), flag('history_worker'), days(120)]),
  ),
  H('med-history-sailor', 'Rafael', 'Denizci',
    'Denizi bilen çok, gördüğünü doğru anlatan azdır. Sen hangisi olacaksın?', 'SEA',
    c('learn', 'Önce dinlemeyi öğrenirim.', 'Deniz çevresindeki haberleri toplamaya başla.', [change('sailorNetwork', 3), change('information', 2), flag('history_listener'), days(140)]),
    c('stay', 'Ben karada kalırım.', 'Liman hayatındaki bağlantılarını güçlendir.', [change('portReputation', 3), change('money', 2), flag('history_worker'), days(140)]),
  ),
  H('med-history-trader', 'Hassan', 'Tüccar',
    'Bir tüccarın maldan önce habere ihtiyacı vardır. Fiyatı değil, hareketi bilmek para kazandırır.', 'TRADE',
    c('ask', 'Hangi haberi arıyorsun?', 'Ticari bilgi ile siyasi bilgi arasındaki sınırı görmeye başla.', [change('merchantNetwork', 3), change('information', 2), flag('history_trade'), days(130)]),
    c('decline', 'Ben yalnızca mal satarım.', 'Ticaret ağını daha dar tut.', [change('money', 3), change('safety', 1), days(130)]),
  ),
  H('med-history-interpreter', 'Giovanni', 'Dil bilen aracı',
    'Bir sözün anlamı bazen kelimelerinde değil, kimin söylediğinde saklıdır.', 'IDENTITY',
    c('learn-language', 'O halde kimin söylediğini sorarım.', 'Dil ve insan ilişkilerinin değerini öğren.', [change('language', 4), change('social', 2), flag('history_interpreter'), days(130)]),
    c('keep-distance', 'Sözü olduğu gibi aktarırım.', 'Aracılıkta mesafeni koru.', [change('language', 2), change('safety', 2), days(130)]),
  ),
  H('med-history-network', 'Yusuf', 'Haber taşıyan kişi',
    'Venedik, Ragusa ve Habsburg limanlarından gelen haberlerin hepsi aynı değerde değildir.', 'INTELLIGENCE',
    c('source', 'Kaynağı kim?', 'Bilginin kaynağını sorgula ve ağını güçlendir.', [change('intelligenceNetwork', 4), change('information', 3), flag('history_source_test'), days(150)]),
    c('rumor', 'Haberi önce dinleyeyim.', 'Kaynağı belirsiz bilgiyi ayırmayı öğren.', [change('information', 4), change('reputation', -1), flag('history_rumor'), days(150)]),
    { weight: 25 },
  ),
  H('med-history-letter', 'Yusuf', 'Aracı',
    'Bu mektup sana geldi. İçinde ne olduğunu bilmek zorunda değilsin; kime ulaşacağını bilmen yeter.', 'INTELLIGENCE',
    c('refuse', 'Bunu taşımayacağım.', 'Riskli bir bağlantıyı reddet.', [change('safety', 4), change('intelligenceNetwork', -1), flag('refused_letter'), days(120)]),
    c('accept', 'Kime teslim edeceğim?', 'Bir haber ağının içine daha fazla gir.', [change('intelligenceNetwork', 5), change('reputation', 2), flag('carried_history_letter'), days(120)]),
    { weight: 28 },
  ),
  H('med-history-captive', 'Mehmed', 'Dönmüş esir',
    'Yıllarca başka limanlarda kaldım. İnsan, esaretin kendisinden çok orada öğrendiklerini yanında getiriyor.', 'CAPTIVITY',
    c('listen', 'Orada ne öğrendin?', 'Yaşadıklarını bir bilgi kaynağı olarak dinle.', [change('information', 5), change('social', 2), flag('heard_captive'), days(150)]),
    c('avoid', 'Geçmişini kurcalamayacağım.', 'Mesafeni koru.', [change('safety', 2), days(150)]),
    { weight: 22 },
  ),
  H('med-history-muhtedi', 'Ahmed', 'Mühtedi denizci',
    'İki dünyanın dilini de biliyorum. Bu yüzden ikisine de tam olarak ait sayılmıyorum.', 'IDENTITY',
    c('ask-people', 'Seni kimler dinliyor?', 'Kimlik değişiminin bilgi ağlarına etkisini öğren.', [change('intelligenceNetwork', 3), change('language', 3), flag('trusted_convert'), days(150)]),
    c('ask-life', 'Burada nasıl yaşıyorsun?', 'Kimlik ve aidiyetin gündelik tarafını gör.', [change('social', 4), change('language', 2), flag('heard_identity'), days(150)]),
    { weight: 22 },
  ),
  H('med-history-counter', 'Mehmet', 'Liman görevlisi',
    'Son günlerde kimlerle konuştuğunu soruyorlar. Her haberin bir de geri dönüşü vardır.', 'INTELLIGENCE',
    c('open', 'Kimlerle konuştuysam söylerim.', 'Şeffaflıkla şüpheyi azalt.', [change('safety', 3), change('intelligenceNetwork', -1), flag('open_questioning'), days(120)]),
    c('protect', 'Bunu anlatmam.', 'Bir bağlantıyı korurken dikkat çekme riskini al.', [change('intelligenceNetwork', 3), change('safety', -3), flag('protected_contact'), days(120)]),
    { weight: 30 },
  ),
  H('med-history-disinformation', 'Yusuf', 'Eski bağlantı',
    'Bazen yanlış haber, doğru haberden daha hızlı gider. Ama geri dönüşü de daha sert olabilir.', 'INTELLIGENCE',
    c('verify', 'Önce doğrulayalım.', 'Bilginin güvenilirliğini sınamayı seç.', [change('information', 4), change('reputation', 2), flag('verified_information'), days(130)]),
    c('pass', 'Bunu yaymayalım.', 'Belirsiz bilgiyi dolaşıma sokma.', [change('safety', 2), change('intelligenceNetwork', 2), flag('withheld_rumor'), days(130)]),
    { weight: 25 },
  ),
  H('med-history-ragusa', 'Bir tüccar', 'Ragusa bağlantısı',
    'Ragusa üzerinden gelen haberler bazen İstanbulda duyulmadan önce limana ulaşır.', 'TRADE',
    c('ask-channel', 'Bu haber sana nasıl ulaştı?', 'Haberin dolaşım yolunu araştır.', [change('merchantNetwork', 4), change('information', 3), flag('ragusa_channel'), days(160)]),
    c('ask-price', 'Bu haberin bedeli ne?', 'Bilginin ticari değerini sorgula.', [change('money', 3), change('merchantNetwork', 2), flag('paid_information'), days(160)]),
    { weight: 24 },
  ),
  H('med-history-habsburg', 'Yusuf', 'Haberci',
    'Habsburg tarafında da insanlar aynı soruyu soruyor: Osmanlı ne hazırlıyor?', 'INTELLIGENCE',
    c('share', 'Biz de ne bildiğimizi düşünelim.', 'Karşı tarafın bilgi arayışını fark et.', [change('information', 4), change('intelligenceNetwork', 3), flag('habsburg_interest'), days(150)]),
    c('stay-silent', 'Bunu konuşmayalım.', 'Bilgiyi paylaşmadan geri çekil.', [change('safety', 4), change('social', -1), days(150)]),
    { weight: 26 },
  ),
  H('med-history-cerbe', 'Bir liman sakini', 'Haberci',
    'Cerbeden gelen haber herkesin dilinde. Akdenizde dengelerin değiştiğini söyleyenler var.', 'SEA',
    c('listen', 'Ne olduğunu anlat.', 'Büyük bir deniz olayının liman hayatına etkisini dinle.', [change('information', 5), change('social', 2), flag('cerbe_news'), days(180)]),
    c('family', 'Bu haber evdekileri etkiler mi?', 'Büyük olayların kişisel hayata etkisini düşün.', [change('familyTies', 2), change('information', 2), flag('cerbe_news'), days(180)]),
    { weight: 35 },
  ),
  H('med-history-after-cerbe', 'Hassan', 'Tüccar',
    'Denizlerdeki değişiklik fiyatları da insanları da etkiliyor. Herkes yeni bir hesap yapıyor.', 'TRADE',
    c('trade', 'Ben de hesabımı yeniden yaparım.', 'Ticaret ağını yeni şartlara göre düzenle.', [change('money', 4), change('merchantNetwork', 4), days(180)]),
    c('information', 'Önce ne değiştiğini öğrenelim.', 'Bilgiyi paradan önce tut.', [change('information', 4), change('intelligenceNetwork', 2), days(180)]),
    { weight: 30 },
  ),
  H('med-history-malta', 'Yusuf', 'Haberci',
    'Maltadan gelen haberler limandaki bütün konuşmaları değiştirdi. Şimdi herkes karşı tarafın niyetini anlamaya çalışıyor.', 'INTELLIGENCE',
    c('ask', 'Kim ne biliyor?', 'Bilgi ağlarının birbirini nasıl beslediğini araştır.', [change('information', 5), change('intelligenceNetwork', 4), flag('malta_news'), days(180)]),
    c('distance', 'Ben bu işten uzak durayım.', 'Kendini büyük siyasi rekabetin dışında tut.', [change('safety', 4), change('social', -1), flag('malta_news'), days(180)]),
    { weight: 38 },
  ),
  H('med-history-inquiry', 'Mehmet', 'Soruşturmacı',
    'Bir mektup, bir tüccar ve bir denizci aynı hikâyede buluşuyor. Sence tesadüf mü?', 'INTELLIGENCE',
    c('connect', 'Üçünün bağlantısını arayalım.', 'Farklı bilgi kaynaklarını tek bir ağ olarak düşün.', [change('intelligenceNetwork', 5), change('information', 4), flag('connected_case'), days(150)]),
    c('separate', 'Her birini ayrı değerlendirelim.', 'Bilgileri birbirine karıştırmadan ilerle.', [change('safety', 3), change('information', 2), flag('separate_sources'), days(150)]),
    { weight: 32 },
  ),
  H('med-history-lepanto', 'Bir denizci', 'Liman sakini',
    'İnebahtıdan sonra herkes denizde yeni bir dönemin başladığını konuşuyor.', 'SEA',
    c('listen', 'Sonuçlarını dinleyelim.', 'Büyük bir deniz savaşının haber ve ticaret dünyasına etkisini öğren.', [change('information', 5), change('reputation', 2), flag('lepanto_news'), days(200)]),
    c('home', 'Artık eve dönmeyi düşünüyorum.', 'Kişisel hayatı ve güvenliği öne çıkar.', [change('familyTies', 5), change('safety', 3), flag('lepanto_news'), days(200)]),
    { weight: 40 },
  ),
  H('med-history-final-network', 'Yusuf', 'Eski bağlantı',
    'Yıllar içinde öğrendiğin bir şey varsa o da haberin tek başına güç olmadığıdır.', 'INTELLIGENCE',
    c('people', 'Asıl güç insanlarda.', 'İlişkileri ve güveni hayatının merkezine koy.', [change('social', 5), change('intelligenceNetwork', 4), flag('history_people'), days(180)]),
    c('distance', 'Ben artık kendi hayatıma bakacağım.', 'Ağlardan uzaklaşıp daha sakin bir yol seç.', [change('safety', 5), change('intelligenceNetwork', -2), flag('history_withdrawn'), days(180)]),
    { weight: 45 },
  ),
  H('med-history-final-port', 'Liman sakini', 'Eski tanıdık',
    'Bunca yıldan sonra liman yine aynı görünüyor. Ama sen artık aynı insan değilsin.', 'PORT',
    c('stay', 'Burada kalacağım.', 'Liman dünyasında öğrendiklerini sürdür.', [change('portReputation', 5), change('merchantNetwork', 2), days(220)]),
    c('leave', 'Başka bir hayata başlayacağım.', 'Limanın dışındaki hayatı seç.', [change('familyTies', 4), change('safety', 4), days(220)]),
    { requires: { lepanto_news: true }, weight: 45 }),
  H('med-history-merchant-source', 'Bir tüccar', 'Tüccar',
    'Tüccarlar uzak limanlardan haber getiriyor. Ama her duyduğunu doğru sayamazsın.', 'TRADE',
    c('cross-check', 'Başka kimden duydun?', 'Aynı bilgiyi farklı kaynaklarla karşılaştır.', [change('information', 4), change('merchantNetwork', 3), flag('merchant_crosscheck'), days(120)]),
    c('trust', 'Sana güveniyorum.', 'Tüccarın güvenini kazan ama bilgiyi daha az sınamış ol.', [change('merchantNetwork', 4), change('reputation', 1), days(120)]),
    { weight: 27 },
  ),
  H('med-history-captive-source', 'Dönmüş esir', 'Esaretten dönmüş kişi',
    'Bir esirin yanında getirdiği haber, bazen bir tüccarın getirdiğinden daha değerli olabilir.', 'CAPTIVITY',
    c('ask-place', 'Hangi limanlardan geçtin?', 'Gördüğü yerleri ve bağlantıları anlamaya çalış.', [change('information', 5), change('social', 2), flag('captive_route'), days(140)]),
    c('ask-people', 'Kimlerle konuştun?', 'İnsan bağlantılarını bilgi kaynağı olarak değerlendir.', [change('intelligenceNetwork', 4), change('information', 3), flag('captive_contacts'), days(140)]),
    { weight: 25 },
  ),
  H('med-history-intermediary', 'Giovanni', 'Aracı',
    'Ben ne tamamen bir elçiyim ne de yalnızca bir tüccar. İki tarafın arasında kalıyorum.', 'IDENTITY',
    c('use-position', 'Arada olmak işine yarıyor mu?', 'Aracılığın bilgi ve ilişki değerini öğren.', [change('social', 4), change('intelligenceNetwork', 3), flag('trusted_intermediary'), days(130)]),
    c('keep-distance', 'Taraflardan uzak dur.', 'Aracılığın riskini azalt.', [change('safety', 3), change('social', 1), days(130)]),
    { weight: 25 },
  ),
  H('med-history-diplomacy', 'Bir elçinin aracısı', 'Aracı',
    'Bir elçi geldiğinde herkes aynı şeyi söylemez. Kimin neyi bilmek istediğini anlamak gerekir.', 'INTELLIGENCE',
    c('ask-purpose', 'Asıl ne öğrenmek istiyor?', 'Diplomatik temasın bilgi boyutunu sorgula.', [change('information', 4), change('intelligenceNetwork', 3), flag('diplomatic_purpose'), days(120)]),
    c('stay-neutral', 'Ben yalnızca aracıyım.', 'Sözlerini sınırlı tut ve mesafeni koru.', [change('safety', 3), change('social', 2), days(120)]),
    { weight: 24 },
  ),
  H('med-history-menzil', 'Yolcu', 'Haberci',
    'Bir haberin değeri, zamanında ulaşmasına da bağlı. Yollar uzadıkça haber eskir.', 'INTELLIGENCE',
    c('secure-route', 'Haberin yolunu sağlam tutalım.', 'Haberin dolaşımındaki güven ve sürekliliği önemse.', [change('intelligenceNetwork', 4), change('safety', 2), flag('reliable_route'), days(150)]),
    c('wait', 'Acele etmeyelim.', 'Daha güvenli ama daha yavaş ilerle.', [change('safety', 3), change('information', 1), days(150)]),
    { weight: 22 },
  ),
  H('med-history-status', 'Bir görevli', 'Görevli',
    'Bazı insanlar düzenli görev alıyor, bazıları ise ihtiyaç çıktığında haber taşıyor.', 'INTELLIGENCE',
    c('learn-system', 'Kimden ne zaman haber alıyorsunuz?', 'Bilgi ağının tek bir merkezden ibaret olmadığını öğren.', [change('information', 4), change('intelligenceNetwork', 3), flag('decentralized_network'), days(150)]),
    c('keep-small', 'Ben küçük çevremle yetineyim.', 'Küçük bir ağla daha kontrollü ilerle.', [change('safety', 3), change('social', 1), days(150)]),
    { weight: 23 },
  ),
  H('med-history-diplomatic-letter', 'Bir kâtip', 'Kâtip',
    'Bir mektubun kime gittiği kadar kimlerin onu okuyabileceği de önemlidir.', 'INTELLIGENCE',
    c('protect-letter', 'Mektubun yolunu koruyalım.', 'Yazışmanın güvenliğine öncelik ver.', [change('safety', 3), change('reputation', 1), flag('protected_correspondence'), days(110)]),
    c('learn-letter', 'İçeriğinden çok yolunu anlamak istiyorum.', 'Yazışma ağının nasıl çalıştığını araştır.', [change('information', 4), change('intelligenceNetwork', 3), flag('correspondence_network'), days(110)]),
    { weight: 26 },
  ),
  H('med-history-questioning', 'Mehmet', 'Soruşturmacı',
    'Bir haber şüpheli çıktığında önce kaynağı, sonra onu taşıyanları sorarız.', 'INTELLIGENCE',
    c('ask-source', 'Önce kaynağa bakalım.', 'Soruşturmayı bilginin kökeninden başlat.', [change('information', 4), change('safety', 2), flag('source_questioning'), days(120)]),
    c('ask-network', 'Kimler bu haberi taşıdı?', 'Haberin arkasındaki bağlantıları takip et.', [change('intelligenceNetwork', 5), change('safety', -1), flag('network_questioning'), days(120)]),
    { weight: 30 },
  ),
  H('med-history-counter-check', 'Bir liman görevlisi', 'Kontrol görevlisi',
    'Sınır ve limanlarda gelenlerin kim olduğu kadar nereden geldiği de soruluyor.', 'PORT',
    c('check', 'Kayıtları karşılaştıralım.', 'Kimlik ve haber bilgisini birlikte kontrol et.', [change('safety', 4), change('information', 3), flag('records_checked'), days(130)]),
    c('trust', 'Herkesi şüpheli görmeyelim.', 'Kontrolü daha hafif tut ve sosyal ilişkileri koru.', [change('social', 3), change('safety', -1), days(130)]),
    { weight: 28 },
  ),
  H('med-history-decision', 'Yusuf', 'Eski bağlantı',
    'Bunca haberin içinden karar vermek zor. En önemli mesele, hangi bilginin gerçekten işe yaradığı.', 'INTELLIGENCE',
    c('compare', 'Önce kaynakları karşılaştıralım.', 'Kararını doğrulanmış bilgiye dayandır.', [change('information', 5), change('reputation', 2), flag('evidence_based'), days(150)]),
    c('act', 'Bildiğimiz kadarı yeter.', 'Eksik bilgiyle karar ver ve hız kazan.', [change('social', 2), change('safety', -2), flag('fast_decision'), days(150)]),
    { weight: 34 },
  ),


  H('med-history-1560-captain', 'Rafael', 'Denizci',
    'Cerbeden dönen gemiler hakkında herkes farklı konuşuyor. Sen ne duydun?', 'SEA',
    c('listen', 'Önce limandaki denizcileri dinleyelim.', 'Farklı anlatıları karşılaştır.', [change('information', 4), change('sailorNetwork', 3), flag('cerbe_sources'), days(45)]),
    c('ask-route', 'Gemiler nereden dönmüş?', 'Haberin geldiği yolu anlamaya çalış.', [change('information', 3), change('intelligenceNetwork', 4), flag('cerbe_route'), days(45)]),
    { minDate: '1560-01-01', maxDate: '1560-12-31', weight: 38 }),
  H('med-history-1560-captive', 'Mehmed', 'Dönmüş esir',
    'Cerbeden sonra limana dönenlerin anlattıkları birbirini tutmuyor.', 'CAPTIVITY',
    c('compare', 'Kim ne anlatıyor?', 'Çelişen anlatıları ayır.', [change('information', 4), change('reputation', 1), flag('captive_accounts'), days(50)]),
    c('listen', 'Biraz daha anlat.', 'Bir kişinin deneyimini daha yakından dinle.', [change('social', 3), change('information', 3), flag('captive_accounts'), days(50)]),
    { minDate: '1560-01-01', maxDate: '1561-12-31', weight: 36 }),
  H('med-history-1561-ragusa', 'Bir Ragusalı', 'Tüccar',
    'Cerbe haberinden sonra Ragusa üzerinden gelen tüccarlar daha fazla soru soruyor.', 'TRADE',
    c('ask', 'Neyi öğrenmek istiyorlar?', 'Ticaret ile haber arasındaki bağlantıyı araştır.', [change('merchantNetwork', 4), change('information', 3), flag('ragusa_after_cerbe'), days(55)]),
    c('wait', 'Önce ne getirdiklerini görelim.', 'Yeni bağlantıya hemen güvenme.', [change('safety', 2), change('merchantNetwork', 2), days(55)]),
    { minDate: '1561-01-01', maxDate: '1563-12-31', weight: 34 }),
  H('med-history-1562-interpreter', 'Giovanni', 'Tercüman',
    'Aynı kişi iki farklı dilde aynı şeyi söylemiyor. Sence sorun nerede?', 'IDENTITY',
    c('word', 'Kelimeleri karşılaştıralım.', 'Çevirinin ayrıntılarını kontrol et.', [change('language', 4), change('information', 2), flag('translation_check'), days(40)]),
    c('person', 'Önce konuşanı tanıyalım.', 'Sözün bağlamını ve kişiyi araştır.', [change('social', 3), change('intelligenceNetwork', 3), flag('speaker_context'), days(40)]),
    { minDate: '1562-01-01', maxDate: '1564-12-31', weight: 32 }),
  H('med-history-1564-letter', 'Bir kâtip', 'Yazıcı',
    'Bir mektup geldi. Kimin gönderdiği belli değil ama bazı isimler tanıdık.', 'INTELLIGENCE',
    c('names', 'İsimleri karşılaştıralım.', 'Mektubu başka bilgilerle kontrol et.', [change('information', 4), change('reputation', 2), flag('anonymous_letter'), days(45)]),
    c('distance', 'Bunu üzerime almayayım.', 'Belirsiz bir bağlantıdan uzak dur.', [change('safety', 3), days(45)]),
    { minDate: '1564-01-01', maxDate: '1565-12-31', weight: 35 }),
  H('med-history-1565-malta-news', 'Bir denizci', 'Haberci',
    'Malta çevresindeki haberler limana ulaştı. Herkes karşı tarafın ne yapacağını soruyor.', 'SEA',
    c('listen', 'Kim ne söylüyor?', 'Farklı çevrelerden gelen haberleri karşılaştır.', [change('information', 5), change('sailorNetwork', 3), flag('malta_sources'), days(60)]),
    c('home', 'Ben ailemi düşünürüm.', 'Büyük olayların kişisel hayatına etkisini öne çıkar.', [change('familyTies', 4), change('safety', 2), flag('malta_family'), days(60)]),
    { minDate: '1565-01-01', maxDate: '1566-12-31', weight: 42 }),
  H('med-history-1566-malta-aftermath', 'Hassan', 'Tüccar',
    'Malta çevresindeki hareketlilik ticareti de etkiledi. Eski hesapların bazıları artık geçerli değil.', 'TRADE',
    c('adjust', 'Hesabı yeniden yapalım.', 'Değişen şartlara göre ticaret çevreni düzenle.', [change('money', 4), change('merchantNetwork', 4), flag('malta_trade'), days(70)]),
    c('learn', 'Önce ne değiştiğini öğrenelim.', 'Ticari değişimin arkasındaki haberleri araştır.', [change('information', 4), change('merchantNetwork', 2), days(70)]),
    { minDate: '1566-01-01', maxDate: '1567-12-31', weight: 38 }),
  H('med-history-1567-venice', 'Venedikli tüccar', 'Yabancı tüccar',
    'Venedikte deniz yollarının nasıl değişeceği konuşuluyor. Burada da bunu soranlar var.', 'TRADE',
    c('ask', 'Hangi yollar değişecek?', 'Ticaret bilgisini daha geniş bir ağa bağla.', [change('merchantNetwork', 4), change('information', 4), flag('venice_route'), days(65)]),
    c('careful', 'Ben yalnızca limandaki işime bakarım.', 'Dış bağlantıyı sınırlı tut.', [change('money', 3), change('safety', 2), days(65)]),
    { minDate: '1567-01-01', maxDate: '1568-12-31', weight: 36 }),
  H('med-history-1568-ragusa-broker', 'Bir aracı', 'Ragusa bağlantısı',
    'İki tarafın da tanıdığı insanlar var. Asıl mesele kimin kime güvendiği.', 'IDENTITY',
    c('trust', 'Güven nerede başlıyor?', 'Aracılık ağının insan tarafını araştır.', [change('social', 4), change('intelligenceNetwork', 4), flag('ragusa_trust'), days(55)]),
    c('names', 'İsimleri bilmem yeter.', 'Bağlantıları kaydet ama fazla yaklaşma.', [change('information', 3), change('safety', 2), days(55)]),
    { minDate: '1568-01-01', maxDate: '1569-12-31', weight: 34 }),
  H('med-history-1569-cyprus', 'Bir haberci', 'Haberci',
    'Doğu Akdenizden gelen haberler çoğaldı. Limanda herkes bir şey bekliyor.', 'INTELLIGENCE',
    c('sources', 'Haberleri ayıralım.', 'Farklı kaynakların ne söylediğini karşılaştır.', [change('information', 5), change('intelligenceNetwork', 3), flag('east_mediterranean_sources'), days(60)]),
    c('family', 'Evdekilere haber vereyim.', 'Belirsizliği aile çevrenle paylaş.', [change('familyTies', 3), change('social', 2), days(60)]),
    { minDate: '1569-01-01', maxDate: '1570-12-31', weight: 40 }),
  H('med-history-1570-cyprus', 'Bir tüccar', 'Tüccar',
    'Kıbrıs çevresinden gelen haberler ticaret hesaplarını da değiştirebilir.', 'TRADE',
    c('ask-route', 'Hangi yollar etkilenir?', 'Ticaret ağının değişen koşullara nasıl tepki verdiğini öğren.', [change('merchantNetwork', 4), change('information', 4), flag('cyprus_trade'), days(70)]),
    c('hold', 'Biraz bekleyelim.', 'Belirsizlik azalıncaya kadar daha temkinli ilerle.', [change('safety', 3), change('money', 1), days(70)]),
    { minDate: '1570-01-01', maxDate: '1571-12-31', weight: 45 }),
  H('med-history-1571-before-lepanto', 'Rafael', 'Denizci',
    'Denizde büyük bir hareketlilik var. Limandaki herkes aynı soruyu soruyor: sonra ne olacak?', 'SEA',
    c('listen', 'Denizciler ne söylüyor?', 'Yaklaşan gelişmeleri farklı kişilerden dinle.', [change('sailorNetwork', 5), change('information', 4), flag('lepanto_tension'), days(45)]),
    c('stay', 'Ben limanda kalacağım.', 'Belirsiz dönemde karada kalmayı seç.', [change('safety', 4), change('portReputation', 2), days(45)]),
    { minDate: '1571-01-01', maxDate: '1571-12-31', weight: 50 }),
  H('med-history-1571-after-lepanto', 'Bir liman görevlisi', 'Görevli',
    'İnebahtı haberi geldi. Şimdi herkes yeni durumun limana ne getireceğini konuşuyor.', 'PORT',
    c('compare', 'Önce farklı haberleri karşılaştıralım.', 'Savaş haberinin çevredeki etkisini bilgi kaynaklarıyla değerlendir.', [change('information', 5), change('reputation', 2), flag('lepanto_aftermath'), days(75)]),
    c('home', 'Önce evdekilere haber vereyim.', 'Tarihsel gelişmeyi kişisel hayatın üzerinden karşıla.', [change('familyTies', 5), change('safety', 3), flag('lepanto_aftermath'), days(75)]),
    { minDate: '1571-01-01', maxDate: '1572-12-31', weight: 52 }),

  H('med-epilogue-1', 'Yusuf', 'Eski bağlantı',
    'İnebahtıdan sonra yıllar geçti. Limanlar değişti, insanlar değişti. Sen hangi hayatı sürdürmek istiyorsun?', 'INTELLIGENCE',
    c('network', 'Bağlantılarımı koruyacağım.', 'Eski bilgi çevreni sonraki yıllara taşı.', [change('intelligenceNetwork', 4), change('reputation', 2), flag('med_path_network'), days(2400)]),
    c('shore', 'Artık daha sakin yaşayacağım.', 'Daha güvenli ve düzenli bir hayata yönel.', [change('safety', 4), change('familyTies', 3), flag('med_path_quiet'), days(2400)]),
    { weight: 50 }),
  H('med-epilogue-2', 'Hassan', 'Eski tüccar',
    'Yıllar içinde ticaret yolları yeniden düzenlendi. Senin limandaki yerin de buna göre değişti.', 'TRADE',
    c('trade', 'Ticarete devam edeceğim.', 'Liman bağlantılarını kalıcı bir geçime dönüştür.', [change('merchantNetwork', 5), change('money', 4), flag('med_path_trade'), days(2400)]),
    c('family', 'Artık aileme daha çok vakit ayıracağım.', 'Ticaretin yanında daha yerleşik bir hayat kur.', [change('familyTies', 5), change('safety', 3), flag('med_path_family'), days(2400)]),
    { weight: 50 }),
  H('med-epilogue-3', 'Giovanni', 'Eski aracı',
    '1580lerden sonra yeni insanlar ve yeni haber yolları ortaya çıktı. Eski çevrenden hangisini yanında taşıyacaksın?', 'IDENTITY',
    c('information', 'Haber ağını sürdüreceğim.', 'Farklı limanlardan gelen bilgileri birbirine bağla.', [change('intelligenceNetwork', 5), change('information', 4), flag('med_path_network'), days(2400)]),
    c('sea', 'Denizden tamamen kopmayacağım.', 'Deniz çevresindeki ilişkilerini sürdür.', [change('sailorNetwork', 5), change('safety', -1), flag('med_path_sea'), days(2400)]),
    { weight: 50 }),
  H('med-epilogue-4', 'Meryem', 'Aileden biri',
    '1590lara geldik. Artık gençliğindeki liman hayatından çok daha fazlasını gördün. Geride ne bırakmak istiyorsun?', 'FAMILY',
    c('family', 'Ailemle kalacağım.', 'Son yıllarını aile bağlarını güçlendirmeye ayır.', [change('familyTies', 6), change('safety', 4), flag('med_path_family'), flag('mediterranean_ended'), days(2400)]),
    c('world', 'Kendi yoluma devam edeceğim.', 'Deniz, ticaret ve bilgi çevrelerinden öğrendiklerini yanında taşı.', [change('reputation', 4), change('social', 3), flag('med_path_quiet'), flag('mediterranean_ended'), days(2400)]),
    { weight: 50 }),

];
