import type { DecisionEffect } from '@/domain/game';
import type { MediterraneanCardDefinition, MediterraneanChoice } from './deck';

const change = (key: string, delta: number): DecisionEffect => ({ type: 'CHANGE_VARIABLE', key, delta });
const flag = (key: string, value = true): DecisionEffect => ({ type: 'SET_FLAG', key, value });
const days = (value: number): DecisionEffect => ({ type: 'ADVANCE_DAYS', days: value });

const c = (idSuffix: string, label: string, description: string, effects: DecisionEffect[]): MediterraneanChoice =>
  ({ idSuffix, label, description, effects });

const H = (
  id: string, speaker: string, role: string, line: string,
  category: MediterraneanCardDefinition['category'],
  left: MediterraneanChoice, right: MediterraneanChoice,
  extra: Partial<MediterraneanCardDefinition> = {},
): MediterraneanCardDefinition => ({
  id, speaker, role, line, category, left, right, weight: 20, ...extra,
});

/**
 * Original game writing informed by the two Emrah Safa Gürkan source books.
 * Historical research is transformed into game situations; source prose is not copied.
 */
export const HISTORICAL_MEDITERRANEAN_CARDS: MediterraneanCardDefinition[] = [
  H('med-history-port', 'Yusuf', 'Liman aracısı',
    'İstanbuldan gelen haberler burada çabuk yayılır. Senin kulağın da açık olsun.', 'INTELLIGENCE',
    c('listen', 'Önce haberi dinleyeyim.', 'Liman çevresindeki bilgi akışına gir.', [change('information', 3), change('social', 2), flag('history_listener'), days(120)]),
    c('work', 'Ben işime bakarım.', 'Daha güvenli bir başlangıç yap.', [change('money', 3), change('safety', 2), flag('history_worker'), days(120)]),
  ),
  H('med-history-sailor', 'Rafael', 'Denizci',
    'Denizi bilen çok, gördüğünü doğru anlatan azdır. Sen hangisi olacaksın?', 'SEA',
    c('learn', 'Önce dinlemeyi öğrenirim.', 'Deniz çevresindeki haberleri toplamaya başla.', [change('sailorNetwork', 3), change('information', 2), flag('history_listener'), days(140)]),
    c('stay', 'Ben karada kalırım.', 'Liman hayatındaki bağlantılarını güçlendir.', [change('portReputation', 3), change('money', 2), flag('history_worker'), days(140)]),
  ),
  H('med-history-trader', 'Hassan', 'Tüccar',
    'Bir tüccarın maldan önce habere ihtiyacı vardır. Fiyatı değil, hareketi bilmek para kazandırır.', 'TRADE',
    c('ask', 'Hangi haberi arıyorsun?', 'Ticari bilgi ile siyasi bilgi arasındaki sınırı görmeye başla.', [change('merchantNetwork', 3), change('information', 2), flag('history_trade'), days(130)]),
    c('decline', 'Ben yalnızca mal satarım.', 'Ticaret ağını daha dar tut.', [change('money', 3), change('safety', 1), days(130)]),
  ),
  H('med-history-interpreter', 'Giovanni', 'Dil bilen aracı',
    'Bir sözün anlamı bazen kelimelerinde değil, kimin söylediğinde saklıdır.', 'IDENTITY',
    c('learn-language', 'O halde kimin söylediğini sorarım.', 'Dil ve insan ilişkilerinin değerini öğren.', [change('language', 4), change('social', 2), flag('history_interpreter'), days(130)]),
    c('keep-distance', 'Sözü olduğu gibi aktarırım.', 'Aracılıkta mesafeni koru.', [change('language', 2), change('safety', 2), days(130)]),
  ),
  H('med-history-network', 'Yusuf', 'Haber taşıyan kişi',
    'Venedik, Ragusa ve Habsburg limanlarından gelen haberlerin hepsi aynı değerde değildir.', 'INTELLIGENCE',
    c('source', 'Kaynağı kim?', 'Bilginin kaynağını sorgula ve ağını güçlendir.', [change('intelligenceNetwork', 4), change('information', 3), flag('history_source_test'), days(150)]),
    c('rumor', 'Haberi önce dinleyeyim.', 'Kaynağı belirsiz bilgiyi ayırmayı öğren.', [change('information', 4), change('reputation', -1), flag('history_rumor'), days(150)]),
    { weight: 25 },
  ),
  H('med-history-letter', 'Yusuf', 'Aracı',
    'Bu mektup sana geldi. İçinde ne olduğunu bilmek zorunda değilsin; kime ulaşacağını bilmen yeter.', 'INTELLIGENCE',
    c('refuse', 'Bunu taşımayacağım.', 'Riskli bir bağlantıyı reddet.', [change('safety', 4), change('intelligenceNetwork', -1), flag('refused_letter'), days(120)]),
    c('accept', 'Kime teslim edeceğim?', 'Bir haber ağının içine daha fazla gir.', [change('intelligenceNetwork', 5), change('reputation', 2), flag('carried_history_letter'), days(120)]),
    { weight: 28 },
  ),
  H('med-history-captive', 'Mehmed', 'Dönmüş esir',
    'Yıllarca başka limanlarda kaldım. İnsan, esaretin kendisinden çok orada öğrendiklerini yanında getiriyor.', 'CAPTIVITY',
    c('listen', 'Orada ne öğrendin?', 'Yaşadıklarını bir bilgi kaynağı olarak dinle.', [change('information', 5), change('social', 2), flag('heard_captive'), days(150)]),
    c('avoid', 'Geçmişini kurcalamayacağım.', 'Mesafeni koru.', [change('safety', 2), days(150)]),
    { weight: 22 },
  ),
  H('med-history-muhtedi', 'Ahmed', 'Mühtedi denizci',
    'İki dünyanın dilini de biliyorum. Bu yüzden ikisine de tam olarak ait sayılmıyorum.', 'IDENTITY',
    c('ask-people', 'Seni kimler dinliyor?', 'Kimlik değişiminin bilgi ağlarına etkisini öğren.', [change('intelligenceNetwork', 3), change('language', 3), flag('trusted_convert'), days(150)]),
    c('ask-life', 'Burada nasıl yaşıyorsun?', 'Kimlik ve aidiyetin gündelik tarafını gör.', [change('social', 4), change('language', 2), flag('heard_identity'), days(150)]),
    { weight: 22 },
  ),
  H('med-history-counter', 'Mehmet', 'Liman görevlisi',
    'Son günlerde kimlerle konuştuğunu soruyorlar. Her haberin bir de geri dönüşü vardır.', 'INTELLIGENCE',
    c('open', 'Kimlerle konuştuysam söylerim.', 'Şeffaflıkla şüpheyi azalt.', [change('safety', 3), change('intelligenceNetwork', -1), flag('open_questioning'), days(120)]),
    c('protect', 'Bunu anlatmam.', 'Bir bağlantıyı korurken dikkat çekme riskini al.', [change('intelligenceNetwork', 3), change('safety', -3), flag('protected_contact'), days(120)]),
    { weight: 30 },
  ),
  H('med-history-disinformation', 'Yusuf', 'Eski bağlantı',
    'Bazen yanlış haber, doğru haberden daha hızlı gider. Ama geri dönüşü de daha sert olabilir.', 'INTELLIGENCE',
    c('verify', 'Önce doğrulayalım.', 'Bilginin güvenilirliğini sınamayı seç.', [change('information', 4), change('reputation', 2), flag('verified_information'), days(130)]),
    c('pass', 'Bunu yaymayalım.', 'Belirsiz bilgiyi dolaşıma sokma.', [change('safety', 2), change('intelligenceNetwork', 2), flag('withheld_rumor'), days(130)]),
    { weight: 25 },
  ),
  H('med-history-ragusa', 'Bir tüccar', 'Ragusa bağlantısı',
    'Ragusa üzerinden gelen haberler bazen İstanbulda duyulmadan önce limana ulaşır.', 'TRADE',
    c('ask-channel', 'Bu haber sana nasıl ulaştı?', 'Haberin dolaşım yolunu araştır.', [change('merchantNetwork', 4), change('information', 3), flag('ragusa_channel'), days(160)]),
    c('ask-price', 'Bu haberin bedeli ne?', 'Bilginin ticari değerini sorgula.', [change('money', 3), change('merchantNetwork', 2), flag('paid_information'), days(160)]),
    { weight: 24 },
  ),
  H('med-history-habsburg', 'Yusuf', 'Haberci',
    'Habsburg tarafında da insanlar aynı soruyu soruyor: Osmanlı ne hazırlıyor?', 'INTELLIGENCE',
    c('share', 'Biz de ne bildiğimizi düşünelim.', 'Karşı tarafın bilgi arayışını fark et.', [change('information', 4), change('intelligenceNetwork', 3), flag('habsburg_interest'), days(150)]),
    c('stay-silent', 'Bunu konuşmayalım.', 'Bilgiyi paylaşmadan geri çekil.', [change('safety', 4), change('social', -1), days(150)]),
    { weight: 26 },
  ),
  H('med-history-cerbe', 'Bir liman sakini', 'Haberci',
    'Cerbeden gelen haber herkesin dilinde. Akdenizde dengelerin değiştiğini söyleyenler var.', 'SEA',
    c('listen', 'Ne olduğunu anlat.', 'Büyük bir deniz olayının liman hayatına etkisini dinle.', [change('information', 5), change('social', 2), flag('cerbe_news'), days(180)]),
    c('family', 'Bu haber evdekileri etkiler mi?', 'Büyük olayların kişisel hayata etkisini düşün.', [change('familyTies', 2), change('information', 2), flag('cerbe_news'), days(180)]),
    { weight: 35 },
  ),
  H('med-history-after-cerbe', 'Hassan', 'Tüccar',
    'Denizlerdeki değişiklik fiyatları da insanları da etkiliyor. Herkes yeni bir hesap yapıyor.', 'TRADE',
    c('trade', 'Ben de hesabımı yeniden yaparım.', 'Ticaret ağını yeni şartlara göre düzenle.', [change('money', 4), change('merchantNetwork', 4), days(180)]),
    c('information', 'Önce ne değiştiğini öğrenelim.', 'Bilgiyi paradan önce tut.', [change('information', 4), change('intelligenceNetwork', 2), days(180)]),
    { weight: 30 },
  ),
  H('med-history-malta', 'Yusuf', 'Haberci',
    'Maltadan gelen haberler limandaki bütün konuşmaları değiştirdi. Şimdi herkes karşı tarafın niyetini anlamaya çalışıyor.', 'INTELLIGENCE',
    c('ask', 'Kim ne biliyor?', 'Bilgi ağlarının birbirini nasıl beslediğini araştır.', [change('information', 5), change('intelligenceNetwork', 4), flag('malta_news'), days(180)]),
    c('distance', 'Ben bu işten uzak durayım.', 'Kendini büyük siyasi rekabetin dışında tut.', [change('safety', 4), change('social', -1), flag('malta_news'), days(180)]),
    { weight: 38 },
  ),
  H('med-history-inquiry', 'Mehmet', 'Soruşturmacı',
    'Bir mektup, bir tüccar ve bir denizci aynı hikâyede buluşuyor. Sence tesadüf mü?', 'INTELLIGENCE',
    c('connect', 'Üçünün bağlantısını arayalım.', 'Farklı bilgi kaynaklarını tek bir ağ olarak düşün.', [change('intelligenceNetwork', 5), change('information', 4), flag('connected_case'), days(150)]),
    c('separate', 'Her birini ayrı değerlendirelim.', 'Bilgileri birbirine karıştırmadan ilerle.', [change('safety', 3), change('information', 2), flag('separate_sources'), days(150)]),
    { weight: 32 },
  ),
  H('med-history-lepanto', 'Bir denizci', 'Liman sakini',
    'İnebahtıdan sonra herkes denizde yeni bir dönemin başladığını konuşuyor.', 'SEA',
    c('listen', 'Sonuçlarını dinleyelim.', 'Büyük bir deniz savaşının haber ve ticaret dünyasına etkisini öğren.', [change('information', 5), change('reputation', 2), flag('lepanto_news'), days(200)]),
    c('home', 'Artık eve dönmeyi düşünüyorum.', 'Kişisel hayatı ve güvenliği öne çıkar.', [change('familyTies', 5), change('safety', 3), flag('lepanto_news'), days(200)]),
    { weight: 40 },
  ),
  H('med-history-final-network', 'Yusuf', 'Eski bağlantı',
    'Yıllar içinde öğrendiğin bir şey varsa o da haberin tek başına güç olmadığıdır.', 'INTELLIGENCE',
    c('people', 'Asıl güç insanlarda.', 'İlişkileri ve güveni hayatının merkezine koy.', [change('social', 5), change('intelligenceNetwork', 4), flag('history_people'), days(180)]),
    c('distance', 'Ben artık kendi hayatıma bakacağım.', 'Ağlardan uzaklaşıp daha sakin bir yol seç.', [change('safety', 5), change('intelligenceNetwork', -2), flag('history_withdrawn'), days(180)]),
    { weight: 45 },
  ),
  H('med-history-final-port', 'Liman sakini', 'Eski tanıdık',
    'Bunca yıldan sonra liman yine aynı görünüyor. Ama sen artık aynı insan değilsin.', 'PORT',
    c('stay', 'Burada kalacağım.', 'Liman dünyasında öğrendiklerini sürdür.', [change('portReputation', 5), change('merchantNetwork', 2), days(220)]),
    c('leave', 'Başka bir hayata başlayacağım.', 'Limanın dışındaki hayatı seç.', [change('familyTies', 4), change('safety', 4), days(220)]),
    { requires: { lepanto_news: true }, weight: 45 }),
];
