import type { DecisionEffect } from '@/domain/game';
import type { MediterraneanCardDefinition, MediterraneanChoice } from './deck';

const ch=(k:string,d:number):DecisionEffect=>({type:'CHANGE_VARIABLE',key:k,delta:d});
const fl=(k:string,v=true):DecisionEffect=>({type:'SET_FLAG',key:k,value:v});
const dy=(n:number):DecisionEffect=>({type:'ADVANCE_DAYS',days:n});
const c=(idSuffix:string,label:string,description:string,effects:DecisionEffect[]):MediterraneanChoice=>({idSuffix,label,description,effects});
const S=(id:string,speaker:string,role:string,line:string,category:MediterraneanCardDefinition['category'],left:MediterraneanChoice,right:MediterraneanChoice,source:MediterraneanCardDefinition['source']):MediterraneanCardDefinition=>({id,speaker,role,line,category,left,right,weight:20,source});

/**
 * Historical narrative spine rebuilt from the subjects and historical world
 * treated in Emrah Safa Gürkan's Sultanın Casusları and Sultanın Korsanları.
 * Dialogue and game choices are original; no book passage is reproduced.
 */
export const MEDITERRANEAN_STORY_SPINE: MediterraneanCardDefinition[]=[
S('med-book-01','Liman kâtibi','Haber ağı','Aynı olay limanda üç farklı şekilde anlatılıyor. Tüccar başka, gemici başka, elçi başka söylüyor. Hangisini yazacağız?','INTELLIGENCE',
c('compare','Üçünden de dinleyelim','Aynı haberi farklı kaynaklardan karşılaştır.',[ch('information',5),ch('intelligenceNetwork',3),fl('book_compare_sources'),dy(20)]),
c('one-source','Birine güvenelim','Hızlı hareket et ama tek kaynağın riskini al.',[ch('information',2),ch('safety',-2),fl('book_single_source'),dy(10)]),'BOTH'),
S('med-book-02','Hassan','Tüccar','Bir tüccarın işi yalnız mal taşımak değildir. Hangi geminin nereden geldiği ve hangi limanda ne bulunduğu da konuşulur.','TRADE',
c('listen','Konuşmasını dinlerim','Ticaret bilgisini haber kaynağına dönüştür.',[ch('merchantNetwork',4),ch('information',4),fl('book_trade_source'),dy(30)]),
c('leave','İşime bakarım','Bilgi kazanma fırsatını bırakıp daha az görünür kal.',[ch('safety',2),ch('money',1),dy(30)]),'SULTANIN_CASUSLARI'),
S('med-book-03','Yusuf','Aracı','Bir haberin İstanbul’a ulaşması için bazen bir devlet görevlisinden çok bir liman aracısı gerekir. Kimin kimi tanıdığı burada para kadar önemli.','INTELLIGENCE',
c('meet','Aracıyı tanırım','Haber ağındaki insanları çoğalt.',[ch('intelligenceNetwork',5),ch('merchantNetwork',2),fl('book_intermediary'),dy(35)]),
c('distance','Mesafemi korurum','Ağın içine girmeden güvenliğini koru.',[ch('safety',3),dy(20)]),'SULTANIN_CASUSLARI'),
S('med-book-04','Yusuf','Haberci','Mektubun değeri yalnız içindeki sözlerde değildir. Onu kimin taşıdığı ve kimin eline geçtiği de haberin parçasıdır.','INTELLIGENCE',
c('carry','Ben taşırım','Haber zincirine doğrudan gir.',[ch('intelligenceNetwork',5),ch('reputation',2),ch('safety',-3),fl('book_message_carrier'),dy(40)]),
c('carrier','Başkasını bulalım','Kendini geri çekip başka bir aracı bul.',[ch('merchantNetwork',2),ch('safety',2),dy(25)]),'SULTANIN_CASUSLARI'),
S('med-book-05','Mehmet','Liman görevlisi','Bazı haberler sadakatle değil ödeme karşılığında gelir. Para alan adamın bilgisi işe yarayabilir; ama neden para istediğini de sormalısın.','INTELLIGENCE',
c('pay','Öderim ama doğrularım','Ücretli bilgiyi başka kaynaklarla sınarsın.',[ch('money',-3),ch('information',5),ch('intelligenceNetwork',2),fl('book_paid_source'),dy(25)]),
c('refuse','Para vermem','Başka bilgi kanallarına yönel.',[ch('money',2),ch('information',1),dy(20)]),'SULTANIN_CASUSLARI'),
S('med-book-06','Yusuf','Eski bağlantı','Haber toplamak kadar başkasının senin hakkında ne topladığını bilmek de önemli. Son günlerde seni soranların sayısı arttı.','INTELLIGENCE',
c('trace','Beni kim soruyor öğrenirim','Kendi çevrendeki karşı istihbarat izlerini araştır.',[ch('information',4),ch('safety',-3),fl('book_counterintelligence'),dy(25)]),
c('hide','Ortadan kaybolurum','Ağını yavaşlatıp görünürlüğünü azalt.',[ch('safety',5),ch('intelligenceNetwork',-2),dy(40)]),'SULTANIN_CASUSLARI'),
S('med-book-07','Elçi','Yabancı temsilci','Venedik ve Habsburg dünyasından gelen haberler limanda birbirine karışıyor. Aynı gelişme farklı devletlerde farklı anlam taşıyor.','INTELLIGENCE',
c('compare-rivals','Haberleri karşılaştırırım','Rakiplerin bakışlarını aynı tabloya koy.',[ch('information',6),ch('intelligenceNetwork',3),dy(45)]),
c('ignore','Siyasete girmem','Kendini liman işlerine kapat.',[ch('safety',3),ch('portReputation',2),dy(35)]),'SULTANIN_CASUSLARI'),
S('med-book-08','Denizci','Gazi','Cerbe’den dönenler hâlâ gördüklerini anlatıyor. Bir seferin sonucu kadar, ardından limanlarda oluşan haber akışı da önemlidir.','SEA',
c('listen-campaign','Dönerleri dinlerim','Sefer haberlerini farklı denizcilerden topla.',[ch('information',5),ch('sailorNetwork',4),fl('book_djerba_memory'),dy(35)]),
c('avoid','Kalabalıktan uzak dururum','Söylentinin içine girmeden güvenliğini koru.',[ch('safety',3),dy(20)]),'BOTH'),
S('med-book-09','Salih','Haber taşıyan denizci','Malta’dan gelen haberler bütün konuşmaları değiştirdi. Kim ne biliyor, kimden biliyor, kim neyi saklıyor?','INTELLIGENCE',
c('malta-news','Haberleri toplarım','Farklı kaynakların Malta haberlerini karşılaştır.',[ch('information',7),ch('intelligenceNetwork',4),fl('book_malta_news'),dy(40)]),
c('stay-away','Uzak dururum','Büyük siyasi gelişmenin dışında kal.',[ch('safety',5),ch('social',-1),dy(30)]),'BOTH'),
S('med-book-10','Kaptan','Korsan kaptanı','Bizim dünyamızda herkes aynı yerden gelmez. Denizci, tüccar, kaçak, mühtedi, esir… Aynı güvertede yan yana gelebilir.','SEA',
c('join','Tayfaya katılırım','Deniz çevresinin içine gir ve yeni bir sosyal ağ kur.',[ch('sailorNetwork',7),ch('money',4),ch('safety',-4),fl('book_corsair_crew'),dy(50)]),
c('shore','Karada kalırım','Deniz çevresini dışarıdan gözlemle.',[ch('merchantNetwork',3),ch('safety',3),dy(35)]),'SULTANIN_KORSANLARI'),
S('med-book-11','Giovanni','Mühtedi denizci','Burada insanın geçmişi tek kelimeyle silinmiyor. Eski memleketini, ailesini ve yeni çevresini aynı anda taşıyanlar var.','IDENTITY',
c('listen-past','Hikâyesini dinlerim','Farklı geçmişleri anlamaya çalış.',[ch('information',4),ch('social',4),fl('book_cross_identity'),dy(30)]),
c('respect','Geçmişini sormam','Özel meseleleri açmadan ilişkiyi sürdür.',[ch('safety',2),ch('social',1),dy(20)]),'SULTANIN_KORSANLARI'),
S('med-book-12','Hassan','Tüccar','Denizde elde edilen ganimetin limana gelmesiyle iş bitmez. Onu satacak, taşıyacak ve parasını dolaşıma sokacak insanlar gerekir.','TRADE',
c('market','Liman piyasasını öğrenirim','Deniz ile ticaret arasındaki bağı kur.',[ch('merchantNetwork',6),ch('money',4),fl('book_corsair_market'),dy(45)]),
c('clear','Bu işe bulaşmam','Kazancı reddedip daha güvenli ticarete dön.',[ch('safety',3),dy(25)]),'SULTANIN_KORSANLARI'),
S('med-book-13','Esir denizci','Esir','Deniz yolculuğu benim için özgürlükle bitmedi. Burada insanlar el değiştiriyor, haberler de insanlarla birlikte dolaşıyor.','CAPTIVITY',
c('listen-captive','Seni dinlerim','Esaretin içinden gelen bilgiyi anlamaya çalış.',[ch('information',5),ch('social',2),fl('book_captive_source'),dy(30)]),
c('walk-away','Bu konuşmayı bitirelim','Kendini tehlikeli bir bağdan uzak tut.',[ch('safety',3),dy(15)]),'SULTANIN_KORSANLARI'),
S('med-book-14','Aracı','Esir pazarlığı aracısı','Bir esirin değeri yalnız parayla ölçülmez. Ailesi, tanıdıkları ve onu isteyen kişi pazarlığın parçasıdır.','CAPTIVITY',
c('trace-family','Ailesini araştırırım','Bağlantıların üzerinden pazarlığın arkasındaki insanları bul.',[ch('information',4),ch('merchantNetwork',3),dy(35)]),
c('close-deal','Pazarlığı kapatırım','Maddi yükü üstlenip meseleyi hızlı bitir.',[ch('money',-5),ch('safety',3),dy(25)]),'SULTANIN_KORSANLARI'),
S('med-book-15','Mağripli denizci','Korsan çevresinden biri','Batı Akdeniz’de limanlar birbirinden uzak ama insanlar birbirine yakın. Bir adamın geçmişi yıllar sonra başka bir kıyıda yeniden karşına çıkabilir.','SEA',
c('west-network','Batı ağını öğrenirim','Uzak limanlardaki insan bağlantılarını takip et.',[ch('sailorNetwork',5),ch('information',5),fl('book_west_network'),dy(50)]),
c('east','Doğu Akdeniz’de kalırım','Bildigin limanlarda daha güvenli bir çevre kur.',[ch('portReputation',4),ch('safety',2),dy(40)]),'SULTANIN_KORSANLARI'),
S('med-book-16','Kaptan','Gemi sorumlusu','Gemide hayat yalnız denize açılmaktan ibaret değil. Yemek, hastalık, disiplin ve ibadet düzeni bozulursa herkesin işi zorlaşır.','SEA',
c('order','Düzeni korurum','Tayfanın günlük hayatını düzenli tutmaya yardım et.',[ch('sailorNetwork',3),ch('safety',4),dy(35)]),
c('crew','Tayfayı dinlerim','Güverte ile tayfa arasındaki güveni öne çıkar.',[ch('social',4),ch('safety',-1),dy(35)]),'SULTANIN_KORSANLARI'),
S('med-book-17','Liman sakini','Kıyı sakini','Bazı limanlar denizciler için yalnız sığınak değildir. Haber, mal, esir ve insan burada birbirine bağlanır.','PORT',
c('map-port','Limanı tanırım','Kimin ne iş yaptığını öğren ve ağını kur.',[ch('portReputation',5),ch('merchantNetwork',4),fl('book_port_hub'),dy(40)]),
c('anonymous','Adımı duyurmam','Limanı kullan ama görünürlüğünü düşük tut.',[ch('safety',4),dy(25)]),'BOTH'),
S('med-book-18','Kaçakçı','Aracı','Ticaret ile kaçakçılık arasındaki çizgi her limanda aynı değildir. Sana iş teklif ediyorlar ama bunun haber taşıma tarafı da var.','TRADE',
c('inspect','Önce kimin işine yaradığını öğrenirim','Ticaret ağının arkasındaki ilişkileri çöz.',[ch('information',5),ch('merchantNetwork',4),dy(35)]),
c('refuse-smuggle','Bu işe girmem','Kazancı reddedip görünürlüğünü azalt.',[ch('safety',4),dy(20)]),'SULTANIN_KORSANLARI'),
S('med-book-19','Venedikli tüccar','Yabancı tüccar','Benim malımın yolu İstanbul’a kadar uzanıyor. Sana başka limanlarda kimlerle konuşabileceğini söyleyebilirim.','TRADE',
c('accept','Bağlantıyı alırım','Rakip bir ticaret çevresinden bilgi kazan.',[ch('merchantNetwork',5),ch('information',4),ch('safety',-2),fl('book_venetian_contact'),dy(35)]),
c('decline','Gerek yok','Yabancı bağlantının riskini alma.',[ch('safety',3),dy(20)]),'SULTANIN_CASUSLARI'),
S('med-book-20','Yusuf','Haberci','Bir haberin yanlış olması her zaman kazara olmaz. Bazen insanlar bilerek yanlış bilgi verir ve karşısındakinin ne yapacağını bekler.','INTELLIGENCE',
c('verify','Haberi sınarım','Aynı bilgiyi bağımsız kaynaklarla doğrula.',[ch('information',6),ch('intelligenceNetwork',3),fl('book_disinformation_test'),dy(30)]),
c('spread','Haberi aktarırım','Hız kazanırsın ama yanlış bilgi taşıma riskini alırsın.',[ch('reputation',-3),ch('information',3),ch('safety',-2),dy(15)]),'SULTANIN_CASUSLARI'),
S('med-book-21','Aracı','Gizli bağlantı','Senden artık yalnız haber istenmiyor. Bir rakibin işini aksatacak bir işten söz ediyorlar. Bunun bedeli haber taşımaktan daha ağır olabilir.','INTELLIGENCE',
c('refuse-operation','Buna girmem','Haber ağını koru ama daha büyük bir işe bulaşma.',[ch('safety',4),ch('intelligenceNetwork',-1),dy(25)]),
c('investigate','Önce kim istediğini öğrenirim','Talebin arkasındaki kişiyi ve amacı araştır.',[ch('information',5),ch('safety',-3),fl('book_covert_operation'),dy(30)]),'SULTANIN_CASUSLARI'),
S('med-book-22','Elçi kâtibi','Elçilik çevresi','Elçiler yalnız resmi sözleri taşımaz. Fiyatlar, gemiler, söylentiler ve insanlar hakkında topladıkları bilgiler de karar verenlere ulaşır.','INTELLIGENCE',
c('diplomatic-network','Bu ağı öğrenirim','Elçilik çevresinin bilgi akışını takip et.',[ch('intelligenceNetwork',6),ch('information',5),dy(45)]),
c('local','Liman ağı bana yeter','Kendi çevrene dön.',[ch('portReputation',3),ch('social',2),dy(30)]),'SULTANIN_CASUSLARI'),
S('med-book-23','Salih','Denizci','Kıbrıs seferi konuşuluyor. Limandaki herkes gemilerin, hazırlıkların ve haberlerin peşinde. Senin çevren de bu hareketten etkileniyor.','SEA',
c('watch-cyprus','Hareketi izlerim','Liman haberlerini düzenli biçimde karşılaştır.',[ch('information',6),ch('sailorNetwork',4),ch('safety',-2),fl('book_cyprus_watch'),dy(45)]),
c('stay-shore','Karada kalırım','Büyük seferin dışında kal.',[ch('safety',4),ch('familyTies',2),dy(35)]),'BOTH'),
S('med-book-24','Rafael','Denizci','İnebahtı haberi geldiğinde eski hesapların bir kısmı anlamını kaybetti. Deniz çevresinde kimin yanında durulacağı yeniden konuşuluyor.','SEA',
c('aftermath','Sonrasını takip ederim','Yeni deniz dengelerinin limanlara etkisini öğren.',[ch('information',6),ch('sailorNetwork',4),fl('book_lepanto_aftermath'),dy(40)]),
c('leave-sea','Karaya çekilirim','Deniz çevresinden uzaklaşıp güvenliğini artır.',[ch('safety',5),ch('sailorNetwork',-2),dy(40)]),'BOTH'),
S('med-book-25','Kaptan','Denizci','Korsan çevresi ile devlet arasındaki ilişki dışarıdan göründüğü kadar basit değil. Denizcilerin, limanın ve devletin çıkarları bazen aynı yöne bakıyor.','SEA',
c('understand','İlişkiyi anlamaya çalışırım','Korsanlık ile devlet siyasetinin kesiştiği ağı takip et.',[ch('information',6),ch('intelligenceNetwork',5),fl('book_state_corsair'),dy(50)]),
c('avoid-politics','Siyasetten uzak dururum','Deniz hayatını siyasi bağlardan ayırmaya çalış.',[ch('safety',4),ch('sailorNetwork',2),dy(35)]),'BOTH'),
S('med-book-26','Giovanni','Nev-müslim denizci','Eski memleketime dönsem beni tanıyacaklar. Burada kalırsam ailemi özleyeceğim. Deniz insanın kimliğini değiştirebiliyor ama geçmişini yok etmiyor.','FAMILY',
c('family-message','Ailesine haber ulaştırırım','Eski bağların yeniden kurulmasına yardım et.',[ch('familyTies',5),ch('social',3),fl('book_cross_border_family'),dy(50)]),
c('dont-interfere','Karışmam','Kendi hayatının sınırını koru.',[ch('safety',3),dy(25)]),'SULTANIN_KORSANLARI'),
S('med-book-27','Esir denizci','Esir','Bir esirin kaçışı bazen yalnız cesaretle olmaz. Bir liman, bir gemici veya dışarıdaki bir tanıdık gerekir.','CAPTIVITY',
c('help-network','Yardım ağı kurarım','Kaçış ihtimalini insan bağlantıları üzerinden araştır.',[ch('information',5),ch('intelligenceNetwork',4),ch('safety',-3),fl('book_escape_network'),dy(40)]),
c('no-interference','Karışmam','Başkasının meselesine girme.',[ch('safety',4),dy(20)]),'SULTANIN_KORSANLARI'),
S('med-book-28','Kaptan','Korsan kaptanı','Ganimetin ele geçirilmesi kadar paylaşılması da mesele. Tayfanın payı, kaptanın payı ve limandaki insanların beklentileri var.','TRADE',
c('fair-share','Paylaşımı açık tutarım','Tayfanın güvenini ve sosyal bağlarını öne çıkar.',[ch('social',5),ch('sailorNetwork',3),ch('money',2),fl('book_fair_share'),dy(35)]),
c('own-share','Kendi payımı korurum','Daha çok para kazan ama çevrende güven kaybedebilirsin.',[ch('money',6),ch('social',-3),ch('sailorNetwork',-2),dy(35)]),'SULTANIN_KORSANLARI'),
S('med-book-29','Tüccar','Liman sakini','Korsanlık, ticaret ve hukuk aynı denizde birbirine değiyor. Bir limanda meşru görülen iş başka yerde suç sayılabilir.','TRADE',
c('learn-law','Kuralları öğrenirim','Limanların farklı bakışlarını ve ilişkilerini anlamaya çalış.',[ch('information',5),ch('portReputation',4),dy(40)]),
c('ignore-law','Ben denize bakarım','Hukuki tartışmadan uzak dur.',[ch('safety',-1),ch('sailorNetwork',3),dy(30)]),'SULTANIN_KORSANLARI'),
S('med-book-30','Kaptan','Korsan kaptanı','Deniz sana para, çevre ve hareket veriyor. Aynı deniz seni aileden ve sakin hayattan uzaklaştırıyor.','IDENTITY',
c('choose-sea','Denizi seçiyorum','Korsan çevresindeki hayatını sürdür.',[ch('sailorNetwork',6),ch('money',4),ch('safety',-4),fl('book_sea_life'),dy(90)]),
c('choose-shore','Karaya dönüyorum','Liman ve aile çevresinde yeni bir düzen kur.',[ch('familyTies',5),ch('safety',5),ch('sailorNetwork',-3),fl('book_shore_life'),dy(90)]),'SULTANIN_KORSANLARI'),
S('med-book-31','Yusuf','Eski bağlantı','Yıllar önce aldığın bir haberin kaynağı yeniden ortaya çıktı. Eski bağlantılar unutulmuyor; yalnızca bir süre sessiz kalıyor.','INTELLIGENCE',
c('reopen','Yeniden konuşurum','Eski ağın ne bildiğini öğren.',[ch('information',6),ch('intelligenceNetwork',5),ch('safety',-3),fl('book_old_source'),dy(40)]),
c('close','Geçmişte kalsın','Eski bağlantıyı kapat.',[ch('safety',5),ch('intelligenceNetwork',-2),dy(35)]),'SULTANIN_CASUSLARI'),
S('med-book-32','Hassan','Tüccar','Denizciler limana döndüğünde tüccarlar da hareketleniyor. Aynı insan hem ticaret yapıp hem deniz çevresine mal sağlayabiliyor.','TRADE',
c('bridge','İki ağı birleştiririm','Tüccar ve denizci çevreni birbirine bağla.',[ch('merchantNetwork',5),ch('sailorNetwork',4),fl('book_sea_trade_bridge'),dy(40)]),
c('separate','Ağları ayırırım','İki çevrenin birbirine karışmasını önle.',[ch('safety',3),ch('merchantNetwork',2),dy(30)]),'BOTH'),
S('med-book-33','Yusuf','Karşı istihbarat bağlantısı','Birileri kurduğun ağın nasıl çalıştığını çözmeye başlamış. Mesele artık daha fazla insan tanımak değil, kime güveneceğini seçmek.','INTELLIGENCE',
c('verify-network','Herkesi yeniden sınarım','Bağlantılarını tek tek doğrula.',[ch('information',5),ch('safety',2),ch('intelligenceNetwork',-1),dy(35)]),
c('expand-network','Ağı büyütürüm','Baskıya karşı yeni bağlantılar kur.',[ch('intelligenceNetwork',6),ch('safety',-4),dy(35)]),'SULTANIN_CASUSLARI'),
S('med-book-34','Meryem','Aileden biri','Denizde kurduğun hayat büyüdükçe kıyıda bıraktığın hayat da değişti. Ailen artık senden yalnız para değil, ne zaman döneceğini bilmek istiyor.','FAMILY',
c('letters','Para ve haber gönderirim','Aile bağını ve haberleşmeyi birlikte sürdür.',[ch('familyTies',6),ch('money',-3),fl('book_family_letters'),dy(45)]),
c('stay-sea','Dönmeyeceğimi söylerim','Deniz hayatını açıkça seç.',[ch('sailorNetwork',4),ch('familyTies',-3),dy(35)]),'SULTANIN_KORSANLARI'),
S('med-book-35','Salih','Eski liman tanıdığı','Yıllar önce başlayan küçük haber zinciri artık büyüdü. Tüccarlar, denizciler, aracılar ve eski kaynaklar birbirine bağlanmış durumda.','INTELLIGENCE',
c('keep-network','Ağı korurum','Kurulan bilgi çevresinin içinde kal.',[ch('intelligenceNetwork',7),ch('reputation',4),ch('safety',-4),fl('book_final_network'),dy(120)]),
c('leave-network','Ağı kapatırım','Geçmiş bağlantılardan çekilip kıyıda yeni bir hayat kur.',[ch('safety',7),ch('intelligenceNetwork',-5),fl('book_final_withdrawal'),dy(120)]),'SULTANIN_CASUSLARI'),
S('med-book-36','Kaptan','Korsan kaptanı','Deniz sana bir isim, bir çevre ve bir hayat verdi. Artık hangi limanda nasıl hatırlanacağını seçmen gerekiyor.','SEA',
c('stay-corsair','Denizde kalırım','Korsan çevresindeki hayatı sürdür.',[ch('sailorNetwork',7),ch('money',4),ch('safety',-5),fl('book_final_sea'),dy(180)]),
c('return-shore','Karaya dönerim','Deniz çevresini geride bırak.',[ch('familyTies',5),ch('safety',6),ch('sailorNetwork',-4),fl('book_final_shore'),dy(180)]),'SULTANIN_KORSANLARI'),
S('med-book-37','Yusuf','Eski bağlantı','Başladığın yerdeki küçük haber artık geride kaldı. Bu dünyada insanın kazandığı yalnız para değil: bağlantılar, güven ve bazen geçmişinden taşıdığı yeni bir kimlik.','IDENTITY',
c('ending-network','Beni ağım hatırlasın','Hayatının merkezine insan bağlantılarını koy.',[ch('social',5),fl('story_ending_network'),dy(30)]),
c('ending-shore','Kıyıda bıraktığım hayat hatırlasın','Aile ve güvenliği öne çıkar.',[ch('familyTies',5),ch('safety',4),fl('story_ending_shore'),dy(30)]),'BOTH'),
];