import type { HistoricalEvent } from '@/domain/history';
import { createHistoricalEvent } from '@/domain/history';

export const GERMANY_1933_CHRONOLOGY: HistoricalEvent[] = [
  createHistoricalEvent({
    id: 'de-1933-hitler-appointed-chancellor',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Adolf Hitler appointed Chancellor',
    summary:
      'President Paul von Hindenburg appointed Adolf Hitler Chancellor of Germany.',
    startDate: '1933-01-30',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 10,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-reichstag-fire',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Reichstag fire',
    summary:
      'The Reichstag building burned in Berlin. The regime used the fire to intensify repression of political opponents.',
    startDate: '1933-02-27',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 20,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-reichstag-fire-decree',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Reichstag Fire Decree',
    summary:
      'President Hindenburg issued an emergency decree suspending key constitutional protections and enabling detention and repression of political opponents.',
    startDate: '1933-02-28',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 30,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-reichstag-election',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Reichstag election',
    summary:
      'The Nazi Party won 43.9 percent of the vote and remained dependent on its coalition partner for a parliamentary majority.',
    startDate: '1933-03-05',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 40,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-dachau-established',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Dachau concentration camp established',
    summary:
      'A concentration camp was established outside Dachau for political opponents of the regime.',
    startDate: '1933-03-22',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 50,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-enabling-act',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Enabling Act passed',
    summary:
      'The Reichstag passed the Enabling Act, allowing the government to enact laws without parliamentary consent and providing a cornerstone of the dictatorship.',
    startDate: '1933-03-23',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 60,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-anti-jewish-boycott',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Nationwide anti-Jewish boycott',
    summary:
      'Nazi Party members and affiliated organizations organized a nationwide boycott of Jewish-owned businesses.',
    startDate: '1933-04-01',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 70,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-civil-service-law',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Law for the Restoration of the Professional Civil Service',
    summary:
      'The law excluded Jews and political opponents from civil-service positions, subject to initial exemptions.',
    startDate: '1933-04-07',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 80,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-book-burnings',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Book burnings',
    summary:
      'Pro-Nazi student organizations carried out public book burnings targeting works labeled “un-German,” including works by Jewish authors and political opponents.',
    startDate: '1933-05-10',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 90,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-one-party-state',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Germany becomes a one-party state',
    summary:
      'By July 14, the Nazi Party was the only legal political party in Germany.',
    startDate: '1933-07-14',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 100,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-state-governments-overthrown',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'State governments brought under central control',
    summary:
      'Using emergency powers, the central government displaced state governments and installed Reich commissioners subordinate to Berlin.',
    startDate: '1933-03-09',
    endDate: '1933-03-11',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 45,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-first-coordination-law',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'First law coordinating the states with the Reich',
    summary:
      'Legislation of March 31 further reduced the autonomy of Germany’s federal states and reorganized their legislatures in line with the Reichstag election result.',
    startDate: '1933-03-31',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 65,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-gestapo-created',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Prussian Secret State Police office created',
    summary:
      'Hermann Göring created the Secret State Police office in Prussia from the existing political police apparatus.',
    startDate: '1933-04-26',
    scope: 'REGIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 85,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-free-trade-unions-dismantled',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Free trade unions dismantled',
    summary:
      'Nazi organizations occupied free trade-union offices and dismantled independent union structures as part of the regime’s coordination of public life.',
    startDate: '1933-05-02',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 87,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-forced-sterilization-law',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Forced sterilization law enacted',
    summary:
      'The Law for the Prevention of Offspring with Hereditary Diseases mandated forced sterilization for categories of people targeted by the regime’s racial and eugenic policies.',
    startDate: '1933-07-14',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 105,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-central-organization-german-jews',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Central Organization of German Jews formed',
    summary:
      'German Jewish organizations formed a central representative organization in response to escalating persecution and exclusion.',
    startDate: '1933-09-17',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 110,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-editor-law',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Editor Law tightens control of the press',
    summary:
      'The Editor Law placed journalism under extensive state and professional controls, further restricting an independent press.',
    startDate: '1933-10-04',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 120,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-league-withdrawal-announced',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Withdrawal from the League of Nations announced',
    summary:
      'The German government announced its withdrawal from the League of Nations and the Geneva Disarmament Conference.',
    startDate: '1933-10-14',
    scope: 'INTERNATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 130,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-reich-culture-chamber',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Reich Culture Chamber established',
    summary:
      'The Reich Culture Chamber consolidated state supervision over major fields of cultural production under the Propaganda Ministry.',
    startDate: '1933-11-15',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 140,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-party-state-law',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Law on the unity of party and state',
    summary:
      'A December law formally bound the Nazi Party to the state as a public-law corporation and further institutionalized the one-party dictatorship.',
    startDate: '1933-12-01',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 150,
    status: 'PUBLISHED',
  }),
];

export function getGermany1933Chronology(): HistoricalEvent[] {
  return [...GERMANY_1933_CHRONOLOGY];
}
