import type { HistoricalEvent } from '@/domain/history';
import { createHistoricalEvent } from '@/domain/history';

export const GERMANY_1933_CHRONOLOGY: HistoricalEvent[] = [
  createHistoricalEvent({
    id: 'de-1933-hitler-appointed-chancellor',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Adolf Hitler appointed Chancellor',
    summary:
      'President Paul von Hindenburg appointed Adolf Hitler Chancellor of Germany.',
    startDate: '1933-01-30',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 10,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-reichstag-fire',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Reichstag fire',
    summary:
      'The Reichstag building burned in Berlin. The regime used the fire to intensify repression of political opponents.',
    startDate: '1933-02-27',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 20,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-reichstag-fire-decree',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Reichstag Fire Decree',
    summary:
      'President Hindenburg issued an emergency decree suspending key constitutional protections and enabling detention and repression of political opponents.',
    startDate: '1933-02-28',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 30,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-reichstag-election',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Reichstag election',
    summary:
      'The Nazi Party won 43.9 percent of the vote and remained dependent on its coalition partner for a parliamentary majority.',
    startDate: '1933-03-05',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 40,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-dachau-established',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Dachau concentration camp established',
    summary:
      'A concentration camp was established outside Dachau for political opponents of the regime.',
    startDate: '1933-03-22',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 50,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-enabling-act',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Enabling Act passed',
    summary:
      'The Reichstag passed the Enabling Act, allowing the government to enact laws without parliamentary consent and providing a cornerstone of the dictatorship.',
    startDate: '1933-03-23',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 60,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-anti-jewish-boycott',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Nationwide anti-Jewish boycott',
    summary:
      'Nazi Party members and affiliated organizations organized a nationwide boycott of Jewish-owned businesses.',
    startDate: '1933-04-01',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 70,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-civil-service-law',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Law for the Restoration of the Professional Civil Service',
    summary:
      'The law excluded Jews and political opponents from civil-service positions, subject to initial exemptions.',
    startDate: '1933-04-07',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 80,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-book-burnings',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Book burnings',
    summary:
      'Pro-Nazi student organizations carried out public book burnings targeting works labeled “un-German,” including works by Jewish authors and political opponents.',
    startDate: '1933-05-10',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 90,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-one-party-state',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Germany becomes a one-party state',
    summary:
      'By July 14, the Nazi Party was the only legal political party in Germany.',
    startDate: '1933-07-14',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 100,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-state-governments-overthrown',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'State governments brought under central control',
    summary:
      'Using emergency powers, the central government displaced state governments and installed Reich commissioners subordinate to Berlin.',
    startDate: '1933-03-09',
    endDate: '1933-03-11',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 45,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-first-coordination-law',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'First law coordinating the states with the Reich',
    summary:
      'Legislation of March 31 further reduced the autonomy of Germany’s federal states and reorganized their legislatures in line with the Reichstag election result.',
    startDate: '1933-03-31',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 65,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-gestapo-created',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Prussian Secret State Police office created',
    summary:
      'Hermann Göring created the Secret State Police office in Prussia from the existing political police apparatus.',
    startDate: '1933-04-26',
    scope: 'REGIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 85,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-free-trade-unions-dismantled',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Free trade unions dismantled',
    summary:
      'Nazi organizations occupied free trade-union offices and dismantled independent union structures as part of the regime’s coordination of public life.',
    startDate: '1933-05-02',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 87,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-forced-sterilization-law',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Forced sterilization law enacted',
    summary:
      'The Law for the Prevention of Offspring with Hereditary Diseases mandated forced sterilization for categories of people targeted by the regime’s racial and eugenic policies.',
    startDate: '1933-07-14',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 105,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-central-organization-german-jews',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Central Organization of German Jews formed',
    summary:
      'German Jewish organizations formed a central representative organization in response to escalating persecution and exclusion.',
    startDate: '1933-09-17',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 110,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-editor-law',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Editor Law tightens control of the press',
    summary:
      'The Editor Law placed journalism under extensive state and professional controls, further restricting an independent press.',
    startDate: '1933-10-04',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 120,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-league-withdrawal-announced',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Withdrawal from the League of Nations announced',
    summary:
      'The German government announced its withdrawal from the League of Nations and the Geneva Disarmament Conference.',
    startDate: '1933-10-14',
    scope: 'INTERNATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 130,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-reich-culture-chamber',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Reich Culture Chamber established',
    summary:
      'The Reich Culture Chamber consolidated state supervision over major fields of cultural production under the Propaganda Ministry.',
    startDate: '1933-11-15',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 140,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-party-state-law',
    eraId: '1933',
    countryIds: ['germany'],
    title: 'Law on the unity of party and state',
    summary:
      'A December law formally bound the Nazi Party to the state as a public-law corporation and further institutionalized the one-party dictatorship.',
    startDate: '1933-12-01',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 150,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-papen-hitler-cologne-talks',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Papen and Hitler hold government-formation talks",
    summary: "Franz von Papen and Adolf Hitler met in Cologne during negotiations that contributed to the political maneuvering preceding the January government change.",
    startDate: '1933-01-04',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 160,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-schleicher-resigns',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Kurt von Schleicher resigns as Chancellor",
    summary: "Kurt von Schleicher resigned after President Hindenburg rejected his requested political course, deepening the government crisis.",
    startDate: '1933-01-28',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 170,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-military-leadership-meeting',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Hitler meets senior military leaders",
    summary: "Four days after becoming Chancellor, Hitler met senior military leaders and outlined broad political and foreign-policy aims.",
    startDate: '1933-02-03',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 180,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-auxiliary-police-prussia',
    eraId: '1933',
    countryIds: ['germany'],
    title: "SA and SS personnel appointed auxiliary police in Prussia",
    summary: "Prussian authorities authorized SA and SS personnel to serve as auxiliary police, increasing coercive pressure on political opponents.",
    startDate: '1933-02-22',
    scope: 'REGIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 190,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-potsdam-day',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Day of Potsdam ceremony",
    summary: "The government staged the Day of Potsdam ceremony at the opening of the new Reichstag to associate the new regime with older Prussian traditions.",
    startDate: '1933-03-21',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 200,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-second-coordination-law',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Reich governors introduced in the federal states",
    summary: "A second coordination law created Reich governor posts, further subordinating Germany’s federal states to the central government.",
    startDate: '1933-04-07',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 210,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-aryan-paragraph-decree',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Ancestry rules for civil servants expanded",
    summary: "An implementing decree for the Civil Service Law defined discriminatory ancestry criteria used to exclude people classified as non-Aryan.",
    startDate: '1933-04-11',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 220,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-school-university-quota-law',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Law restricts Jewish students in schools and universities",
    summary: "A law limited the admission of Jewish students to public schools and universities as part of escalating state discrimination.",
    startDate: '1933-04-25',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 230,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-may-day-state-holiday',
    eraId: '1933',
    countryIds: ['germany'],
    title: "May Day made a state holiday",
    summary: "The government declared May Day a national labor holiday immediately before independent trade unions were dismantled.",
    startDate: '1933-05-01',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 240,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-german-labor-front',
    eraId: '1933',
    countryIds: ['germany'],
    title: "German Labor Front established",
    summary: "After independent unions were dismantled, the German Labor Front was established as the regime-controlled labor organization.",
    startDate: '1933-05-10',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 250,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-youth-organizations-coordinated',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Independent youth organizations brought under centralized pressure",
    summary: "The regime intensified the coordination of youth organizations under Reich Youth Leader Baldur von Schirach.",
    startDate: '1933-06-17',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 260,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-spd-banned',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Social Democratic Party banned",
    summary: "The Social Democratic Party was prohibited and its property confiscated, eliminating the principal remaining parliamentary opposition party.",
    startDate: '1933-06-22',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 270,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-dnvp-dissolves',
    eraId: '1933',
    countryIds: ['germany'],
    title: "German National People’s Party dissolves",
    summary: "The DNVP, the conservative coalition partner that had helped form the January government, dissolved under mounting political pressure.",
    startDate: '1933-06-27',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 280,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-dvp-dissolves',
    eraId: '1933',
    countryIds: ['germany'],
    title: "German People’s Party dissolves",
    summary: "The German People’s Party dissolved as the multi-party political system collapsed.",
    startDate: '1933-07-04',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 290,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-center-party-dissolves',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Centre Party dissolves",
    summary: "The Catholic Centre Party dissolved, removing another major component of the former parliamentary party system.",
    startDate: '1933-07-05',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 300,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-citizenship-revocation-law',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Law permits revocation of recent naturalizations",
    summary: "Legislation authorized the revocation of certain naturalizations and was used disproportionately against people targeted by the regime, including Jews.",
    startDate: '1933-07-14',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 310,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-reich-concordat',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Reich Concordat signed with the Holy See",
    summary: "Germany and the Holy See signed the Reich Concordat regulating the position of the Catholic Church in Germany.",
    startDate: '1933-07-20',
    scope: 'INTERNATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 320,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-culture-chambers-exclusion',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Cultural chambers exclude Jewish professionals",
    summary: "The cultural chamber system denied membership to Jews and others targeted by the regime, excluding them from many cultural professions.",
    startDate: '1933-09-22',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 330,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-hereditary-farm-law',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Hereditary Farm Law enacted",
    summary: "The Hereditary Farm Law tied designated farms to racial ancestry requirements and restricted inheritance and transfer.",
    startDate: '1933-09-29',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 340,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-league-referendum-election',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Regime holds referendum and Reichstag election",
    summary: "A referendum on foreign policy and a single-list Reichstag election were held after opposition parties had been eliminated.",
    startDate: '1933-11-12',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 350,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-habitual-criminals-law',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Law against dangerous habitual criminals enacted",
    summary: "The law expanded preventive detention and coercive criminal-justice measures against people categorized by the regime as habitual criminals.",
    startDate: '1933-11-24',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 360,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-unemployment-reduction-law',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Law to reduce unemployment enacted",
    summary: "The government introduced measures framed as unemployment reduction, including public-works and employment incentives.",
    startDate: '1933-06-01',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 370,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-autobahn-project-announced',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Reich motorway program promoted",
    summary: "The government publicly promoted a national motorway construction program as part of its employment and infrastructure policy.",
    startDate: '1933-06-27',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 380,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-radio-control-consolidated',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Broadcasting placed under tighter central control",
    summary: "During 1933, broadcasting was increasingly centralized under the Propaganda Ministry and used as an instrument of state-controlled mass communication.",
    startDate: '1933-06-30',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 390,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-prussian-academy-exclusions',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Cultural and academic institutions undergo political coordination",
    summary: "During spring 1933, prominent cultural and academic institutions experienced dismissals, resignations and political coordination under the new regime.",
    startDate: '1933-04-15',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 400,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-lawyers-restricted',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Jewish lawyers face professional exclusion",
    summary: "Legislation and administrative measures sharply restricted Jewish lawyers’ ability to practice, with limited initial exemptions.",
    startDate: '1933-04-07',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 410,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-jewish-reichswehr-employees-dismissed',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Jewish employees dismissed from armed-forces service",
    summary: "A government decree required Jewish workers and employees of the Reichswehr to be dismissed from service.",
    startDate: '1933-05-07',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 420,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-geneva-disarmament-exit',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Germany leaves Geneva Disarmament Conference",
    summary: "The government withdrew from the Geneva Disarmament Conference alongside its announced departure from the League of Nations.",
    startDate: '1933-10-14',
    scope: 'INTERNATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 430,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-november-single-list-election',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Single-list Reichstag election held",
    summary: "Voters were presented with a single Nazi-dominated candidate list in a Reichstag election held after Germany had become a one-party state.",
    startDate: '1933-11-12',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 440,
    status: 'PUBLISHED',
  }),
  createHistoricalEvent({
    id: 'de-1933-political-police-centralization',
    eraId: '1933',
    countryIds: ['germany'],
    title: "Political police centralization advances",
    summary: "Across 1933, political police structures were progressively centralized and brought under Nazi control, expanding the dictatorship’s repressive apparatus.",
    startDate: '1933-12-31',
    scope: 'NATIONAL',
    classification: 'HISTORICAL_FACT',
    sortOrder: 450,
    status: 'PUBLISHED',
  }),
];

export function getGermany1933Chronology(): HistoricalEvent[] {
  return [...GERMANY_1933_CHRONOLOGY];
}
