import { createHistoricalSource, type HistoricalSource } from '@/domain/history';

export const GERMANY_1933_RESEARCH_SOURCES: HistoricalSource[] = [
  createHistoricalSource({
    id: 'ushmm-1933-key-dates',
    type: 'MUSEUM_OR_INSTITUTION',
    title: '1933: Key Dates',
    authors: ['United States Holocaust Memorial Museum'],
    editors: [],
    publisher: 'United States Holocaust Memorial Museum',
    publicationYear: null,
    journalOrCollection: 'Holocaust Encyclopedia',
    volume: null,
    issue: null,
    archiveName: null,
    archiveReference: null,
    structuredArchiveReference: null,
    url: 'https://encyclopedia.ushmm.org/content/en/article/1933-key-dates',
    accessedDate: '2026-10-01',
    isbn: null,
    doi: null,
    language: 'en',
    confidence: 'A',
    status: 'VERIFIED',
  }),
  createHistoricalSource({
    id: 'dhm-lemo-1933-chronology',
    type: 'MUSEUM_OR_INSTITUTION',
    title: 'Chronik 1933',
    authors: ['Deutsches Historisches Museum'],
    editors: [],
    publisher: 'Deutsches Historisches Museum',
    publicationYear: null,
    journalOrCollection: 'Lebendiges Museum Online',
    volume: null,
    issue: null,
    archiveName: null,
    archiveReference: null,
    structuredArchiveReference: null,
    url: 'https://www.dhm.de/lemo/jahreschronik/1933',
    accessedDate: '2026-10-01',
    isbn: null,
    doi: null,
    language: 'de',
    confidence: 'A',
    status: 'VERIFIED',
  }),
  createHistoricalSource({
    id: 'dhm-lemo-gleichschaltung',
    type: 'MUSEUM_OR_INSTITUTION',
    title: 'Die Gleichschaltung 1933',
    authors: ['Deutsches Historisches Museum'],
    editors: [],
    publisher: 'Deutsches Historisches Museum',
    publicationYear: null,
    journalOrCollection: 'Lebendiges Museum Online',
    volume: null,
    issue: null,
    archiveName: null,
    archiveReference: null,
    structuredArchiveReference: null,
    url: 'https://www.dhm.de/lemo/kapitel/ns-regime/etablierung/gleichschaltung',
    accessedDate: '2026-10-01',
    isbn: null,
    doi: null,
    language: 'de',
    confidence: 'A',
    status: 'VERIFIED',
  }),
];

export function getGermany1933ResearchSources(): HistoricalSource[] {
  return [...GERMANY_1933_RESEARCH_SOURCES];
}
